import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('http://localhost:8080/realms/aspl-realm/protocol/openid-connect/auth?response_type=code&client_id=aspl-open-id&redirect_uri=http%3A%2F%2Flocalhost%3A3000&code_challenge=UW0Eb3jCQySRSm6IYatJ1DfOG3EhgglgD-rdEW9uM90&code_challenge_method=S256&scope=profile+openid&state=customLoginState');
    await page.getByRole('textbox', { name: 'Username or email' }).click();
    await page.getByRole('textbox', { name: 'Username or email' }).fill('vishalp');
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('12345');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.locator('div').filter({ hasText: 'AMS' }).nth(4).click();
    await page.getByRole('menuitem', { name: 'Admin' }).click();
    await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
    // ---------------------- CREATE AREAS ----------------------
    await page.getByRole('menuitem', { name: 'Area', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Create' }).click();
    await page.getByRole('option', { name: 'Company1' }).click();
    await page.getByRole('textbox', { name: 'Area' }).fill('C1_CCWA_BA1');
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('textbox', { name: 'Area' }).fill('C1_CCWA_BA2');
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('textbox', { name: 'Area' }).fill('C1_CCWA_BA3');
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    // ---------------------- CREATE SUBAREAS ----------------------
    await page.getByRole('menuitem', { name: 'Subarea' }).click();
    await page.getByRole('menuitem', { name: 'Create' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company1' }).click();
    await page.getByRole('combobox', { name: 'Area' }).click();
    await page.getByRole('option', { name: 'C1_CCWA_BA1' }).click();
    await page.getByRole('textbox', { name: 'Subarea' }).fill('C1_CCWA_BA1_SA1');
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Area' }).click();
    await page.getByRole('option', { name: 'C1_CCWA_BA1' }).click();
    await page.getByRole('textbox', { name: 'Subarea' }).fill('C1_CCWA_BA1_SA2');
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Area' }).click();
    await page.getByRole('option', { name: 'C1_CCWA_BA2' }).click();
    await page.getByRole('textbox', { name: 'Subarea' }).fill('C1_CCWA_BA2_SA1');
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    // ---------------------- CREATE QUESTIONS ----------------------
    await page.getByRole('menuitem', { name: 'Admin' }).click();
    await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
    await page.getByRole('menuitem', { name: 'Question' }).click();
    await page.getByRole('menuitem', { name: 'Create' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company1' }).click();
    await page.getByRole('combobox', { name: 'Area' }).click();
    await page.getByRole('option', { name: 'C1_CCWA_BA1' }).click();
    await page.getByRole('combobox', { name: 'Subarea' }).click();
    await page.getByRole('option', { name: 'C1_CCWA_BA1_SA1' }).click();
    await page.getByRole('textbox', { name: 'Question' }).fill('C1_CCWA_BA1_SA1 QUESTION1');
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Area' }).click();
    await page.getByRole('option', { name: 'C1_CCWA_BA1' }).click();
    await page.getByRole('combobox', { name: 'Subarea' }).click();
    await page.getByRole('option', { name: 'C1_CCWA_BA1_SA1' }).click();
    await page.getByRole('textbox', { name: 'Question' }).fill('C1_CCWA_BA1_SA1 QUESTION2');
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Area' }).click();
    await page.getByRole('option', { name: 'C1_CCWA_BA1' }).click();
    await page.getByRole('combobox', { name: 'Subarea' }).click();
    await page.getByRole('option', { name: 'C1_CCWA_BA1_SA2' }).click();
    await page.getByRole('textbox', { name: 'Question' }).fill('C1_CCWA_BA1_SA2 QUESTION');
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Area' }).click();
    await page.getByRole('option', { name: 'C1_CCWA_BA2' }).click();
    await page.getByRole('combobox', { name: 'Subarea' }).click();
    await page.getByRole('option', { name: 'C1_CCWA_BA2_SA1' }).click();
    await page.getByRole('textbox', { name: 'Question' }).fill('C1_CCWA_BA2_SA1 QUESTION');
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Area' }).click();
    await page.getByRole('option', { name: 'C1_CCWA_BA3' }).click();
    await page.getByRole('textbox', { name: 'Question' }).fill('C1_CCWA_BA3 QUESTION');
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
//  ---------------------- Create Audit Type ----------------------
await page.getByRole('menuitem', { name: 'Admin' }).click();
await page.getByRole('menuitem', { name: 'Audit Type' }).click();
await page.getByRole('menuitem', { name: 'Create' }).click();
await page.getByRole('combobox', { name: 'Select Report Type' }).first().click();
await page.getByRole('option', { name: 'Tabular' }).click();
await page.getByRole('textbox', { name: 'Select Color' }).click();
await page.getByRole('textbox', { name: 'Select Color' }).fill('#d3c673');
await page.getByRole('textbox', { name: 'Audit Type Name' }).fill('C1 Concurrent WA');
await page.getByRole('combobox', { name: 'Audit Type Status' }).click();
await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
await page.getByRole('combobox', { name: 'Audit Scoring Method' }).click();
await page.getByRole('option', { name: 'Weightage Average' }).click();
await page.getByRole('combobox', { name: 'Loan Scoring Method' }).click();
await page.getByRole('option', { name: 'Weightage Average' }).click();
await page.getByRole('combobox', { name: 'Frequency' }).click();
await page.getByRole('option', { name: 'Half Yearly' }).click();
await page.getByRole('spinbutton', { name: 'Finding Closure Duration (in' }).fill('7');
await page.getByText('INTERNAL').click();
await page.getByRole('option', { name: 'INTERNAL' }).click();
await page.getByRole('textbox', { name: 'Description' }).click();
await page.getByRole('textbox', { name: 'Description' }).fill('This is the Concurrent WA audit type');
await page.getByRole('radio', { name: 'No' }).check();
await page.getByRole('radio', { name: 'Yes' }).check();
await page.getByRole('button', { name: 'Save' }).click();
await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('button', { name: 'Add Row' }).first().click();
  await page.getByRole('button', { name: 'Add Row' }).first().click();
  await page.getByRole('button', { name: 'Add Row' }).first().click();
  await page.locator('form').getByRole('button', { name: 'Add Row' }).click();
  await page.locator('form').getByRole('button', { name: 'Add Row' }).click();
  await page.locator('#system-alias-select-0').click();
  await page.getByRole('option', { name: 'Open' }).click();
  await page.getByRole('option', { name: 'Open' }).click();
  await page.locator('#system-alias-select-1').click();
  await page.getByRole('option', { name: 'Closed' }).click();
  await page.locator('[id=":r76:"]').click();
  await page.locator('[id=":r76:"]').press('CapsLock');
  await page.locator('[id=":r76:"]').fill('OPEN');
  await page.locator('[id=":r7a:"]').click();
  await page.locator('[id=":r7a:"]').fill('CLOSED');
  await page.getByRole('combobox').first().click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByRole('combobox').nth(1).click();
  await page.getByRole('option', { name: 'NA' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select' }).click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.locator('tr').filter({ hasText: 'YesYESNO' }).getByPlaceholder('Compliance').click();
  await page.locator('tr').filter({ hasText: 'YesYESNO' }).getByPlaceholder('Compliance').fill('YES');
  await page.locator('tr').filter({ hasText: 'NAYESNO' }).getByPlaceholder('Compliance').click();
  await page.locator('tr').filter({ hasText: 'NAYESNO' }).getByPlaceholder('Compliance').fill('NA');
  await page.getByRole('row', { name: 'Delete Row #000000 Add Row' }).getByPlaceholder('Compliance').click();
  await page.getByRole('row', { name: 'Delete Row #000000 Add Row' }).getByPlaceholder('Compliance').fill('N');
  await page.getByRole('row', { name: 'Delete Row N #000000 Add Row' }).getByPlaceholder('Compliance').fill('NO');
  await page.getByRole('row', { name: 'Delete Row YES #000000 Add Row' }).getByLabel('NO').check();
  await page.getByRole('row', { name: 'Delete Row NA #000000 Add Row' }).getByLabel('NO').check();
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByLabel('YES').check();
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByLabel('Add Row').click();
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByLabel('Add Row').click();
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByLabel('Add Row').click();
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByLabel('Add Row').click();
  await page.getByRole('row', { name: 'Delete Row YES #000000 Add Row' }).getByPlaceholder('Weightage').click();
  await page.getByRole('row', { name: 'Delete Row YES #000000 Add Row' }).getByPlaceholder('Weightage').fill('5');
  await page.getByRole('row', { name: 'Delete Row NA #000000 Add Row' }).getByPlaceholder('Weightage').click();
  await page.getByRole('row', { name: 'Delete Row NA #000000 Add Row' }).getByPlaceholder('Weightage').fill('5');
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByPlaceholder('Weightage').click();
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByPlaceholder('Weightage').fill('4');
  await page.getByRole('textbox', { name: 'Weightage' }).first().click();
  await page.getByRole('textbox', { name: 'Weightage' }).first().fill('3');
  await page.getByRole('textbox', { name: 'Weightage' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Weightage' }).nth(1).fill('2');
  await page.getByRole('textbox', { name: 'Weightage' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Weightage' }).nth(1).fill('21');
  await page.getByRole('cell', { name: '21' }).getByPlaceholder('Weightage').click();
  await page.getByRole('cell', { name: '21' }).getByPlaceholder('Weightage').fill('2');
  await page.getByRole('textbox', { name: 'Weightage' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Weightage' }).nth(2).fill('1');
  await page.getByRole('textbox', { name: 'Weightage' }).nth(3).click();
  await page.getByRole('textbox', { name: 'Weightage' }).nth(3).fill('0');
  await page.getByRole('row', { name: 'Delete Row NO 4 #000000 Add' }).getByPlaceholder('Sub Answer').click();
  await page.getByRole('row', { name: 'Delete Row NO 4 #000000 Add' }).getByPlaceholder('Sub Answer').press('CapsLock');
  await page.getByRole('row', { name: 'Delete Row NO 4 #000000 Add' }).getByPlaceholder('Sub Answer').fill('Low');
  await page.getByRole('row', { name: '3 #000000 Delete Row' }).getByPlaceholder('Sub Answer').click();
  await page.getByRole('row', { name: '3 #000000 Delete Row' }).getByPlaceholder('Sub Answer').fill('M');
  await page.getByRole('row', { name: 'M 3 #000000 Delete Row' }).getByPlaceholder('Sub Answer').fill('Medium');
  await page.getByRole('row', { name: '2 #000000 Delete Row' }).getByPlaceholder('Sub Answer').click();
  await page.getByRole('row', { name: '2 #000000 Delete Row' }).getByPlaceholder('Sub Answer').fill('High');
  await page.getByRole('row', { name: '1 #000000 Delete Row' }).getByPlaceholder('Sub Answer').click();
  await page.getByRole('row', { name: '1 #000000 Delete Row' }).getByPlaceholder('Sub Answer').fill('Very High');
  await page.locator('[id=":r7r:"]').click();
  await page.locator('[id=":r7r:"]').fill('Extremely High');
  await page.getByRole('cell', { name: '#' }).nth(1).click();
  await page.getByRole('row', { name: 'Delete Row YES 5 #000000 Add' }).locator('input[type="color"]').fill('#36f2a0');
  await page.getByRole('row', { name: 'Delete Row NA 5 #000000 Add' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: 'Delete Row NA 5 #000000 Add' }).locator('input[type="color"]').fill('#c96fe2');
  await page.getByRole('cell', { name: '#36f2a0' }).first().click();
  await page.getByRole('row', { name: 'Delete Row NO Low 4 #000000' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: 'Delete Row NO Low 4 #000000' }).locator('input[type="color"]').fill('#3dbd81');
  await page.getByRole('cell', { name: '#000000' }).nth(1).click();
  await page.getByRole('row', { name: 'Medium 3 #000000 Delete Row' }).locator('input[type="color"]').fill('#cec55f');
  await page.getByRole('cell', { name: '#000000' }).nth(1).click();
  await page.getByRole('row', { name: 'High 2 #000000 Delete Row' }).locator('input[type="color"]').fill('#b5684f');
  await page.getByRole('cell', { name: '#000000' }).nth(1).click();
  await page.getByRole('row', { name: 'Very High 1 #000000 Delete Row' }).locator('input[type="color"]').fill('#de4f4f');
  await page.getByRole('cell', { name: '#000000' }).nth(1).dblclick();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .MuiTableCell-root > .MuiBox-root').fill('#e01010');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('button', { name: 'Add Row' }).click();
  await page.getByRole('button', { name: 'Add Row' }).click();
  await page.getByRole('button', { name: 'Add Row' }).click();
  await page.getByRole('combobox', { name: 'System Alias' }).first().click();
  await page.getByRole('option', { name: 'Open' }).click();
  await page.getByRole('option', { name: 'Open' }).click();
  await page.getByRole('combobox', { name: 'System Alias' }).nth(1).click();
  await page.getByRole('option', { name: 'Completed' }).click();
  await page.locator('td').filter({ hasText: 'System AliasSystem Alias *' }).getByLabel('System Alias').click();
  await page.getByRole('option', { name: 'Wip' }).click();
  await page.getByRole('cell').first().click();
  await page.locator('tr').filter({ hasText: 'System AliasOpenSystem Alias *' }).getByRole('textbox').press('CapsLock');
  await page.locator('tr').filter({ hasText: 'System AliasOpenSystem Alias *' }).getByRole('textbox').fill('OPEN');
  await page.getByRole('cell').nth(3).click();
  await page.locator('tr').filter({ hasText: 'System AliasCompletedSystem' }).getByRole('textbox').fill('COMPLETED');
  await page.getByRole('row', { name: 'System Alias Remove Row', exact: true }).getByRole('textbox').click();
  await page.getByRole('row', { name: 'System Alias Remove Row', exact: true }).getByRole('textbox').fill('WIP');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('paragraph').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('paragraph').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('spinbutton').first().click();
  await page.locator('[id=":r9i:"]').click();
  await page.locator('[id=":r9i:"]').fill('A');
  await page.locator('[id=":r9a:"]').click();
  await page.locator('[id=":r9a:"]').fill('B');
  await page.locator('[id=":r92:"]').click();
  await page.locator('[id=":r92:"]').fill('C');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('D');
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('E');
  await page.locator('[id=":r9j:"]').click();
  await page.locator('[id=":r9j:"]').fill('EXCELLENT RUN');
  await page.locator('[id=":r9b:"]').click();
  await page.locator('[id=":r9b:"]').fill('WELL RUN');
  await page.locator('[id=":r93:"]').click();
  await page.locator('[id=":r93:"]').fill('FAIRLY WELL RUN');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('SATISFACTORY RUN');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('UNSATISFACTORY RUN');
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('EXTREMELY HIGH RISK');
  await page.locator('input[type="text"]').nth(5).click();
  await page.locator('input[type="text"]').nth(5).fill('H');
  await page.getByRole('cell', { name: 'H', exact: true }).locator('input[type="text"]').fill('HIGH RISK');
  await page.locator('[id=":r94:"]').click();
  await page.getByRole('cell', { name: 'HIGH RISK', exact: true }).click();
  await page.getByRole('cell', { name: 'HIGH RISK', exact: true }).locator('input[type="text"]').press('ArrowLeft');
  await page.getByRole('cell', { name: 'HIGH RISK', exact: true }).locator('input[type="text"]').press('ArrowLeft');
  await page.getByRole('cell', { name: 'HIGH RISK', exact: true }).locator('input[type="text"]').press('ArrowLeft');
  await page.getByRole('cell', { name: 'HIGH RISK', exact: true }).locator('input[type="text"]').press('ArrowLeft');
  await page.getByRole('cell', { name: 'HIGH RISK', exact: true }).locator('input[type="text"]').press('ArrowLeft');
  await page.getByRole('cell', { name: 'HIGH RISK', exact: true }).locator('input[type="text"]').press('ArrowLeft');
  await page.getByRole('cell', { name: 'HIGH RISK', exact: true }).locator('input[type="text"]').press('ArrowLeft');
  await page.getByRole('cell', { name: 'HIGH RISK', exact: true }).locator('input[type="text"]').press('ArrowLeft');
  await page.getByRole('cell', { name: 'HIGH RISK', exact: true }).locator('input[type="text"]').press('ArrowLeft');
  await page.getByRole('cell', { name: 'HIGH RISK', exact: true }).locator('input[type="text"]').press('ArrowLeft');
  await page.getByRole('cell', { name: 'HIGH RISK', exact: true }).locator('input[type="text"]').fill('VERY HIGH RISK');
  await page.locator('[id=":r94:"]').click();
  await page.locator('[id=":r94:"]').fill('HIGH RISK');
  await page.locator('[id=":r9c:"]').click();
  await page.locator('[id=":r9c:"]').fill('MEDIUM RISK');
  await page.locator('[id=":r9k:"]').click();
  await page.locator('[id=":r9k:"]').fill('LOW RISK');
  await page.getByRole('row', { name: '0 50 E UNSATISFACTORY RUN' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: '0 50 E UNSATISFACTORY RUN' }).locator('input[type="color"]').fill('#f10404');
  await page.getByRole('cell', { name: '#' }).nth(1).click();
  await page.getByRole('row', { name: '51 60 D SATISFACTORY RUN VERY' }).locator('input[type="color"]').fill('#ba5a5a');
  await page.getByRole('cell', { name: '#' }).nth(2).click();
  await page.getByRole('row', { name: '61 70 C FAIRLY WELL RUN HIGH RISK #' }).locator('input[type="color"]').fill('#80afc6');
  await page.getByRole('cell', { name: '#' }).nth(3).click();
  await page.getByRole('row', { name: '71 90 B WELL RUN MEDIUM RISK #' }).locator('input[type="color"]').fill('#5dac9c');
  await page.locator('div').filter({ hasText: /^Save$/ }).click();
  await page.locator('div').filter({ hasText: /^Save$/ }).click();
  await page.getByRole('cell', { name: '#000000' }).locator('input[type="color"]').click();
  await page.getByRole('cell', { name: '#000000' }).locator('input[type="color"]').fill('#2bc535');
  await page.getByRole('row', { name: '0 50 E UNSATISFACTORY RUN' }).getByRole('combobox').click();
  await page.getByRole('option', { name: 'Yearly', exact: true }).click();
  await page.getByRole('row', { name: '51 60 D SATISFACTORY RUN VERY' }).getByRole('combobox').click();
  await page.locator('#menu- > .MuiBackdrop-root').click();
  await page.getByText('Yearly').click();
  await page.getByRole('option', { name: 'Monthly' }).click();
  await page.getByRole('row', { name: '91 100 A EXCELLENT RUN LOW' }).getByRole('combobox').click();
  await page.getByRole('option', { name: 'Yearly', exact: true }).click();
  await page.getByRole('row', { name: '90 B WELL RUN MEDIUM RISK #5dac9c' }).getByRole('combobox').click();
  await page.getByRole('option', { name: 'Half Yearly' }).click();
  await page.getByRole('row', { name: '61 70 C FAIRLY WELL RUN HIGH' }).getByRole('combobox').click();
  await page.getByRole('option', { name: 'Quarterly' }).click();
  await page.getByRole('row', { name: '51 60 D SATISFACTORY RUN VERY' }).getByRole('combobox').click();
  await page.getByRole('option', { name: 'Monthly' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Finish' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  // ---------------------- MAP AUDIT TYPE ----------------------
  await page.getByRole('menuitem', { name: 'Admin' }).click();
await page.getByRole('menuitem', { name: 'Audit Type' }).click();
await page.getByRole('menuitem', { name: 'Map AuditType To Area' }).click();
await page.getByRole('combobox', { name: 'Organization' }).click();
await page.getByRole('option', { name: 'Company1' }).click();
await page.getByRole('combobox', { name: 'Audit Type' }).click();
await page.getByRole('option', { name: 'C1 Concurrent WA' }).click();
await page.getByRole('checkbox', { name: 'Mumbai Ho' }).check();
await page.getByRole('button', { name: 'move selected right' }).first().click();
await page.getByRole('checkbox', { name: 'C1_CCWA_BA1' }).check();
await page.getByRole('checkbox', { name: 'C1_CCWA_BA2' }).check();
await page.getByRole('checkbox', { name: 'C1_CCWA_BA3' }).check();
await page.getByRole('button', { name: 'move selected left' }).nth(1).click();
await page.getByPlaceholder('Weightage').nth(0).click();
await page.getByPlaceholder('Weightage').nth(0).fill('50');
await page.getByPlaceholder('Weightage').nth(1).click();
await page.getByPlaceholder('Weightage').nth(1).fill('25');
await page.getByPlaceholder('Weightage').nth(2).click();
await page.getByPlaceholder('Weightage').nth(2).fill('25');
await page.getByRole('button', { name: 'Map' }).click();
await page.getByRole('combobox', { name: 'Organization' }).click();
await page.getByRole('option', { name: 'Company1' }).click();
await page.getByRole('combobox', { name: 'Audit Type' }).click();
await page.getByRole('option', { name: 'C1 Concurrent WA' }).click();
await page.getByRole('checkbox', { name: 'Pune Branch' }).check();
await page.getByRole('button', { name: 'move selected right' }).first().click();
await page.getByRole('checkbox', { name: 'C1_CCWA_BA1' }).check();
await page.getByRole('checkbox', { name: 'C1_CCWA_BA2' }).check();
await page.getByRole('button', { name: 'move selected left' }).nth(1).click();
await page.getByPlaceholder('Weightage').nth(0).click();
await page.getByPlaceholder('Weightage').nth(0).fill('50');
await page.getByPlaceholder('Weightage').nth(1).click();
await page.getByPlaceholder('Weightage').nth(1).fill('50');
await page.getByRole('button', { name: 'Map' }).click();
// -------------Create Workflow-----------------
await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Workflow', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('textbox', { name: 'Workflow Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Name' }).fill('M');
  await page.getByRole('textbox', { name: 'Workflow Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Workflow Name' }).fill('Maker Checker (');
  await page.getByRole('textbox', { name: 'Workflow Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Workflow Name' }).fill('Maker Checker (C1CONCURRENTWA)');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  // ------------------Create Workflow Stages-----------------
  await page.getByRole('link', { name: 'Create Workflow Stages' }).click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'C1 Concurrent WA' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Planned');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Created');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Document Upload');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit In Progress');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Completed');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Review In Progress');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click({
    modifiers: ['Shift']
  });
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Compliance In Progress');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Compliance Review In progress');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Compliance Verification In Progress');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.locator('div').filter({ hasText: /^Submit$/ }).first().click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Compliance Verification Review In Progress');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Closed');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  // ------------------Assign Workflow Stages-----------------
  await page.getByRole('link', { name: 'Assign Sequence to Workflow' }).click();
  await page.getByRole('combobox', { name: 'Stage Workflow' }).click();
  await page.getByRole('option', { name: 'Maker Checker (C1CONCURRENTWA)' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Audit Planned' }).click();
  await page.getByRole('option', { name: 'Audit Planned' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('1');
  await page.getByRole('option', { name: 'Audit Planned' }).click();
  await page.getByRole('option', { name: 'Audit Planned' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage Audit' }).click();
  await page.getByRole('option', { name: 'Audit Created' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('2');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Document Upload' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('3');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Audit In Progress' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('4');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Audit Completed' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('5');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Audit Review In Progress' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('6');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Compliance In Progress' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('7');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Compliance Review In progress' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('8');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('2');
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Compliance Verification In' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('9');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Compliance Verification Review In Progress' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('10');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Audit Closed' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('11');
  await page.getByRole('button', { name: 'Submit' }).click();
  // ------------------Manage Workflow Access-----------------
  await page.getByRole('link', { name: 'Manage Workflow Access' }).click();
  await page.getByRole('combobox', { name: 'Audit Type' }).click();
  await page.getByRole('option', { name: 'C1 Concurrent WA' }).click();
  await page.getByRole('combobox', { name: 'Role' }).click();
  await page.getByRole('option', { name: 'C1OrgAdmin' }).click();
  await page.getByTestId('CheckBoxOutlineBlankIcon').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(3) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(7) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.getByTestId('CheckBoxOutlineBlankIcon').nth(2).click();
  await page.locator('tr:nth-child(2) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.getByTestId('CheckBoxOutlineBlankIcon').nth(5).click();
  await page.locator('tr:nth-child(2) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(9)').click();
  await page.locator('tr:nth-child(10) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(12) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(12) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(4) > td:nth-child(12) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(12) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(8) > td:nth-child(12) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(12) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(11) > td:nth-child(12) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(15) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(15) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(6) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(15) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(11) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(18) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(18) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(7) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(18) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(11) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(20) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(20)').click();
  await page.locator('tr:nth-child(7) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Role C1OrgAdmin' }).click();
  await page.getByRole('option', { name: 'C1Auditor', exact: true }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(3) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(11) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Role C1Auditor' }).click();
  await page.getByRole('option', { name: 'C1Auditee', exact: true }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Role C1Auditee' }).click();
  await page.getByRole('option', { name: 'C1AuditeeReviewer' }).click();
  await page.locator('tr:nth-child(8) > td:nth-child(12) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(11) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(11) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(11) > td:nth-child(11) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(3) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(2) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(8)').click();
  await page.locator('tr:nth-child(9) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Role C1AuditeeReviewer' }).click();
  await page.getByRole('option', { name: 'C1AuditorReviewer' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(8) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(8) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(20) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(10) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('td:nth-child(11) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(11) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(7) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.locator('.MuiPopover-root.MuiModal-root.css-tskh11-MuiModal-root-MuiPopover-root > .MuiBackdrop-root').click();
  await page.locator('.MuiPopover-root.MuiModal-root.css-tskh11-MuiModal-root-MuiPopover-root > .MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Workflow Stages' }).click();
  await page.getByRole('menuitem', { name: 'Manage Workflow Access' }).click();
  // ------------------Define Workflow-----------------
  await page.getByRole('link', { name: 'Define Workflow' }).click();
  await page.getByRole('combobox', { name: 'Audit Type' }).click();
  await page.getByRole('option', { name: 'C1 Concurrent WA' }).click();
  await page.getByRole('combobox', { name: 'Workflow Stages' }).first().click();
  await page.getByRole('option', { name: 'Audit In Progress' }).click();
  await page.getByRole('checkbox', { name: 'Set Audit Actual Start Date' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('form').getByText('Audit In Progress').click();
  await page.getByRole('option', { name: 'Audit Completed' }).click();
  await page.getByRole('checkbox', { name: 'Set Audit Actual Finish Date' }).check();
  await page.getByRole('checkbox', { name: 'Generate Score' }).check();
  await page.getByRole('checkbox', { name: 'Generate Audit Complete Report' }).check();
  await page.getByRole('checkbox', { name: 'Set Udin No' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('form').getByText('Audit Completed').click();
  await page.getByRole('option', { name: 'Compliance In Progress' }).click();
  await page.getByRole('combobox', { name: 'Select Fields' }).click();
  await page.getByRole('option', { name: 'Control Effectiveness' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('form').getByText('Compliance In Progress').click();
  await page.getByRole('option', { name: 'Audit Closed' }).click();
  await page.getByRole('checkbox', { name: 'Set Audit Closed Date' }).check();
  await page.getByRole('checkbox', { name: 'Generate Audit Closed Report' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  // ------------------Create Audit-----------------
  await page.getByRole('menuitem', { name: 'Audit' }).click();
  await page.getByRole('menuitem', { name: 'Audit Annual Plan' }).click();
  await page.getByRole('combobox', { name: 'Audit Type' }).click();
  await page.getByRole('option', { name: 'C1 Concurrent WA' }).click();
  await page.getByRole('combobox', { name: 'Audit Plan for' }).click();
  await page.getByRole('option', { name: 'Calendar Year' }).click();
  await page.getByRole('button', { name: 'Generate', exact: true }).click();
  await page.getByRole('combobox', { name: 'Months of 2025' }).click();
  await page.getByRole('option', { name: 'Jan' }).click();
  await page.getByRole('button', { name: 'Generate Schedule' }).click();
  await page.getByRole('button', { name: 'Initiate Audit' }).click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'Audit Created' }).click();
  await page.getByRole('textbox', { name: 'Planned Start Date' }).fill('2025-01-06');
  await page.getByRole('textbox', { name: 'Planned Start Time' }).click();
  await page.getByRole('textbox', { name: 'Planned Start Time' }).fill('10:30');
  await page.getByRole('textbox', { name: 'Audit Period From' }).fill('2024-12-01');
  await page.getByRole('textbox', { name: 'Audit Period To' }).fill('2024-12-31');
  await page.getByRole('textbox', { name: 'Audit Scope' }).click();
  await page.getByRole('textbox', { name: 'Audit Scope' }).fill('SCOPE');
  await page.getByRole('textbox', { name: 'Audit Objective' }).click();
  await page.getByRole('textbox', { name: 'Audit Objective' }).fill('OBJECTIVE');
  await page.getByRole('button', { name: 'Add Users +' }).click();
  await page.getByRole('button', { name: 'Add Users +' }).click();
  await page.getByRole('button', { name: 'Add Users +' }).click();
  await page.getByRole('button', { name: 'Add Users +' }).click();
  await page.getByRole('button', { name: 'Add Users +' }).click();
  await page.getByRole('combobox', { name: 'Select User' }).first().click();
  await page.getByRole('option', { name: 'c1companyadmin-C1OrgAdmin' }).click();
  await page.getByRole('combobox', { name: 'Select User' }).nth(1).click();
  await page.getByRole('option', { name: 'c1companyauditee-C1Auditee' }).click();
  await page.getByRole('option', { name: 'c1companyauditee-C1Auditee' }).click();
  await page.getByRole('option', { name: 'c1companyauditee-C1Auditee' }).click();
  await page.getByRole('combobox', { name: 'Assign Audit Level Role' }).first().click();
  await page.getByRole('checkbox').uncheck();
  await page.getByText('C1OrgAdmin', { exact: true }).click();
  await page.getByRole('combobox', { name: 'Assign Audit Level Role' }).nth(1).click();
  await page.getByRole('checkbox').uncheck();
  await page.getByText('C1Auditee', { exact: true }).click();
  await page.getByRole('combobox', { name: 'Assign Audit Level Role' }).nth(2).click();
  await page.getByRole('checkbox').uncheck();
  await page.getByText('C1AuditeeReviewer', { exact: true }).click();
  await page.getByRole('combobox', { name: 'Assign Audit Level Role' }).nth(3).click();
  await page.getByRole('checkbox').uncheck();
  await page.getByText('C1Auditor', { exact: true }).click();
  await page.getByRole('checkbox', { name: 'Is Lead Auditor?' }).check();
  await page.getByRole('combobox', { name: 'Assign Audit Level Role' }).nth(4).click();
  await page.getByRole('checkbox').uncheck();
  await page.getByText('C1AuditorReviewer', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Audit Name' }).click();
  await page.getByRole('textbox', { name: 'Audit Name' }).fill('C1 Concurrent WA Jan 2025');
  await page.getByRole('textbox', { name: 'Planned Finish Date' }).fill('2025-01-06');
  await page.getByRole('textbox', { name: 'Planned Finish Time' }).click();
  await page.getByRole('textbox', { name: 'Planned Finish Time' }).fill('18:00');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('menuitem', { name: 'Audit' }).click();
  await page.getByRole('menuitem', { name: 'List View' }).click();
});