import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {

    await page.goto('http://localhost:8080/realms/aspl-realm/protocol/openid-connect/auth?response_type=code&client_id=aspl-open-id&redirect_uri=http%3A%2F%2Flocalhost%3A3000&code_challenge=UW0Eb3jCQySRSm6IYatJ1DfOG3EhgglgD-rdEW9uM90&code_challenge_method=S256&scope=profile+openid&state=customLoginState');
    await page.getByRole('textbox', { name: 'Username or email' }).click();
    await page.getByRole('textbox', { name: 'Username or email' }).fill('vishalp');
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('12345');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.locator('div').filter({ hasText: 'AMS' }).nth(4).click();
    await page.getByRole('menuitem', { name: 'Admin' }).click();
    await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
    // ---------------------- CREATE AREAS ----------------------
await page.getByRole('menuitem', { name: 'Admin' }).click();
await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
await page.getByRole('menuitem', { name: 'Area', exact: true }).click();
await page.getByRole('menuitem', { name: 'Create' }).click();
await page.getByRole('combobox', { name: 'Organization' }).click();
await page.getByRole('option', { name: 'Company1' }).click();
await page.getByRole('textbox', { name: 'Area' }).fill('C1_RBIA_BA1');
await page.getByRole('combobox', { name: 'Status' }).click();
await page.getByRole('option', { name: 'Active', exact: true }).click();
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('textbox', { name: 'Area' }).fill('C1_RBIA_BA2');
await page.getByRole('combobox', { name: 'Status' }).click();
await page.getByRole('option', { name: 'Active', exact: true }).click();
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('textbox', { name: 'Area' }).fill('C1_RBIA_BA3');
await page.getByRole('combobox', { name: 'Status' }).click();
await page.getByRole('option', { name: 'Active', exact: true }).click();
await page.getByRole('button', { name: 'Submit' }).click();
// ---------------------- CREATE SUBAREAS ----------------------
await page.getByRole('menuitem', { name: 'Subarea' }).click();
await page.getByRole('menuitem', { name: 'Create' }).click();
await page.getByRole('combobox', { name: 'Organization' }).click();
await page.getByRole('option', { name: 'Company1' }).click();
await page.getByRole('combobox', { name: 'Area' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA1' }).click();
await page.getByRole('textbox', { name: 'Subarea' }).fill('C1_RBIA_BA1_SA1');
await page.getByRole('combobox', { name: 'Status' }).click();
await page.getByRole('option', { name: 'Active', exact: true }).click();
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('combobox', { name: 'Area' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA1' }).click();
await page.getByRole('textbox', { name: 'Subarea' }).fill('C1_RBIA_BA1_SA2');
await page.getByRole('combobox', { name: 'Status' }).click();
await page.getByRole('option', { name: 'Active', exact: true }).click();
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('combobox', { name: 'Area' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA2' }).click();
await page.getByRole('textbox', { name: 'Subarea' }).fill('C1_RBIA_BA2_SA1');
await page.getByRole('combobox', { name: 'Status' }).click();
await page.getByRole('option', { name: 'Active', exact: true }).click();
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('combobox', { name: 'Area' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA3' }).click();
await page.getByRole('textbox', { name: 'Subarea' }).fill('C1_RBIA_BA3_SA1');
await page.getByRole('combobox', { name: 'Status' }).click();
await page.getByRole('option', { name: 'Active', exact: true }).click();
await page.getByRole('button', { name: 'Submit' }).click();
// ---------------------- CREATE QUESTIONS ----------------------
await page.getByRole('menuitem', { name: 'Admin' }).click();
await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
await page.getByRole('menuitem', { name: 'Question' }).click();
await page.getByRole('menuitem', { name: 'Create' }).click();
await page.getByRole('combobox', { name: 'Organization' }).click();
await page.getByRole('option', { name: 'Company1' }).click();
await page.getByRole('combobox', { name: 'Area' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA1' }).click();
await page.getByRole('combobox', { name: 'Subarea' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA1_SA1' }).click();
await page.getByRole('textbox', { name: 'Question' }).fill('C1_RBIA_BA1_SA1 QUESTION1');
await page.getByRole('combobox', { name: 'Status' }).click();
await page.getByRole('option', { name: 'Active' }).click();
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('textbox', { name: 'Question' }).fill('C1_RBIA_BA1_SA1 QUESTION2');
await page.getByRole('combobox', { name: 'Status' }).click();
await page.getByRole('option', { name: 'Active' }).click();
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('combobox', { name: 'Area' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA1' }).click();
await page.getByRole('combobox', { name: 'Subarea' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA1_SA2' }).click();
await page.getByRole('textbox', { name: 'Question' }).fill('C1_RBIA_BA1_SA2 QUESTION');
await page.getByRole('combobox', { name: 'Status' }).click();
await page.getByRole('option', { name: 'Active' }).click();
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('combobox', { name: 'Area' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA2' }).click();
await page.getByRole('combobox', { name: 'Subarea' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA2_SA1' }).click();
await page.getByRole('textbox', { name: 'Question' }).fill('C1_RBIA_BA2_SA1 QUESTION');
await page.getByRole('combobox', { name: 'Status' }).click();
await page.getByRole('option', { name: 'Active' }).click();
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('combobox', { name: 'Area' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA3' }).click();
await page.getByRole('combobox', { name: 'Subarea' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA3_SA1' }).click();
await page.getByRole('textbox', { name: 'Question' }).fill('C1_RBIA_BA3_SA1 QUESTION');
await page.getByRole('combobox', { name: 'Status' }).click();
await page.getByRole('option', { name: 'Active' }).click();
await page.getByRole('button', { name: 'Submit' }).click();
// ----------------------CREATE DOCUMENTS----------------------
await page.getByRole('menuitem', { name: 'Admin' }).click();
await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
await page.getByRole('menuitem', { name: 'Document' }).click();
await page.getByRole('menuitem', { name: 'Create' }).click();
await page.getByRole('combobox', { name: 'Organization' }).click();
await page.getByRole('option', { name: 'Company1' }).click();
await page.getByRole('combobox', { name: 'Area' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA1' }).click();
await page.getByRole('combobox', { name: 'Subarea' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA1_SA1' }).click();
await page.getByRole('combobox', { name: 'Question' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA1_SA1 QUESTION1' }).click();
await page.getByRole('textbox', { name: 'Document Name' }).fill('C1_RBIA_AuditLevelDocument1');
await page.getByRole('combobox', { name: 'Category' }).click();
await page.getByRole('option', { name: 'AUDITOR' }).click();
await page.getByRole('combobox', { name: 'Document Type' }).click();
await page.getByRole('option', { name: 'Annexure' }).click();
await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_RBIA_AuditLevelDocument1.xlsx');
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('textbox', { name: 'Document Name' }).fill('C1_RBIA_AuditorDocument1');
await page.getByRole('combobox', { name: 'Category' }).click();
await page.getByRole('option', { name: 'AUDITOR' }).click();
await page.getByRole('combobox', { name: 'Document Type' }).click();
await page.getByRole('option', { name: 'Supporting' }).click();
await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_RBIA_AuditorDocument1.pdf');
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('textbox', { name: 'Document Name' }).fill('C1_RBIA_AuditLevelDocument2');
await page.getByRole('combobox', { name: 'Category' }).click();
await page.getByRole('option', { name: 'AUDITOR' }).click();
await page.getByRole('combobox', { name: 'Document Type' }).click();
await page.getByRole('option', { name: 'Annexure' }).click();
await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_RBIA_AuditLevelDocument2.xlsx');
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('combobox', { name: 'Subarea' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA1_SA2' }).click();
await page.getByRole('combobox', { name: 'Question' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA1_SA2 QUESTION' }).click();
await page.getByRole('textbox', { name: 'Document Name' }).fill('C1_RBIA_AuditorDocument2');
await page.getByRole('combobox', { name: 'Category' }).click();
await page.getByRole('option', { name: 'AUDITOR' }).click();
await page.getByRole('combobox', { name: 'Document Type' }).click();
await page.getByRole('option', { name: 'Supporting' }).click();
await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_RBIA_AuditorDocument2.pdf');
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('textbox', { name: 'Document Name' }).fill('C1_RBIA_AuditeeDocument1');
await page.getByRole('combobox', { name: 'Category' }).click();
await page.getByRole('option', { name: 'AUDITEE' }).click();
await page.getByRole('combobox', { name: 'Document Type' }).click();
await page.getByRole('option', { name: 'Supporting' }).click();
await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_RBIA_AuditeeDocument1.pdf');
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('combobox', { name: 'Area' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA2' }).click();
await page.getByRole('combobox', { name: 'Subarea' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA2_SA1' }).click();
await page.getByRole('combobox', { name: 'Question' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA2_SA1 QUESTION' }).click();
await page.getByRole('textbox', { name: 'Document Name' }).fill('C1_RBIA_AuditeeDocument2');
await page.getByRole('combobox', { name: 'Category' }).click();
await page.getByRole('option', { name: 'AUDITEE' }).click();
await page.getByRole('combobox', { name: 'Document Type' }).click();
await page.getByRole('option', { name: 'Supporting' }).click();
await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_RBIA_AuditeeDocument2.pdf');
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('combobox', { name: 'Area' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA3' }).click();
await page.getByRole('combobox', { name: 'Subarea' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA3_SA1' }).click();
await page.getByRole('combobox', { name: 'Question' }).click();
await page.getByRole('option', { name: 'C1_RBIA_BA3_SA1 QUESTION' }).click();
await page.getByRole('textbox', { name: 'Document Name' }).fill('C1_RBIA_AuditorDocument3');
await page.getByRole('combobox', { name: 'Category' }).click();
await page.getByRole('option', { name: 'AUDITOR' }).click();
await page.getByRole('combobox', { name: 'Document Type' }).click();
await page.getByRole('option', { name: 'Supporting' }).click();
await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_RBIA_AuditorDocument3.pdf');
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('textbox', { name: 'Document Name' }).fill('C1_RBIA_AuditorDocument4');
await page.getByRole('combobox', { name: 'Category' }).click();
await page.getByRole('option', { name: 'AUDITOR' }).click();
await page.getByRole('combobox', { name: 'Document Type' }).click();
await page.getByRole('option', { name: 'Supporting' }).click();
await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_RBIA_AuditorDocument4.pdf');
await page.getByRole('button', { name: 'Submit' }).click();
    // -------------Create Audit Type-----------------
    await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Audit Type' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Select Report Type' }).first().click();
  await page.getByRole('option', { name: 'Tabular' }).click();
  await page.getByRole('textbox', { name: 'Audit Type Name' }).click();
  await page.getByRole('textbox', { name: 'Audit Type Name' }).fill('C1 RBIA');
  await page.getByRole('combobox', { name: 'Audit Type Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('combobox', { name: 'Audit Scoring Method' }).click();
  await page.getByRole('option', { name: 'RBIA' }).click();
  await page.getByRole('combobox', { name: 'Loan Scoring Method' }).click();
  await page.getByRole('option', { name: 'RBIA' }).click();
  await page.getByRole('combobox', { name: 'Frequency' }).click();
  await page.getByRole('option', { name: 'Yearly', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Finding Closure Duration (in' }).click();
  await page.getByRole('spinbutton', { name: 'Finding Closure Duration (in' }).fill('15');
  await page.getByRole('combobox', { name: 'Select Report Type' }).nth(1).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('THIS IS RBIA AUDIT TYPE');
  await page.getByRole('radio', { name: 'Yes' }).check();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.locator('input[name=":r6c:"]').check();
  await page.locator('input[name=":r6e:"]').check();
  await page.locator('input[name=":r6c:"]').check();
  await page.locator('input[name=":r6b:"]').check();
  await page.locator('input[name=":r6d:"]').check();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('row', { name: '2320229521587456' }).getByRole('checkbox').check();
  await page.getByRole('row', { name: '2320230220506304' }).getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('button', { name: 'Add Row' }).click();
  await page.getByRole('button', { name: 'Add Row' }).click();
  await page.getByRole('button', { name: 'Add Row' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('LOW');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('MEDIUM');
  await page.getByRole('row', { name: 'Remove', exact: true }).getByRole('textbox').click();
  await page.getByRole('row', { name: 'Remove', exact: true }).getByRole('textbox').fill('HIGH');
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('spinbutton').first().fill('1');
  await page.getByRole('spinbutton').nth(4).click();
  await page.getByRole('spinbutton').nth(4).fill('2');
  await page.locator('[id=":r7a:"]').click();
  await page.locator('[id=":r7a:"]').fill('3');
  await page.getByRole('spinbutton').nth(1).click();
  await page.getByRole('spinbutton').nth(1).fill('13');
  await page.getByRole('spinbutton').nth(5).click();
  await page.getByRole('spinbutton').nth(1).click();
  await page.getByRole('spinbutton').nth(1).fill('1');
  await page.getByRole('spinbutton').nth(5).click();
  await page.getByRole('spinbutton').nth(1).fill('12');
  await page.getByRole('spinbutton').nth(1).click();
  await page.getByRole('spinbutton').nth(1).fill('1');
  await page.getByRole('spinbutton').nth(5).click();
  await page.getByRole('spinbutton').nth(5).fill('2');
  await page.locator('[id=":r7b:"]').click();
  await page.locator('[id=":r7b:"]').fill('3');
  await page.getByRole('spinbutton').nth(2).click();
  await page.getByRole('spinbutton').nth(2).fill('1');
  await page.locator('[id=":r76:"]').click();
  await page.locator('[id=":r76:"]').fill('4');
  await page.locator('[id=":r7c:"]').click();
  await page.locator('[id=":r7c:"]').fill('9');
  await page.getByRole('spinbutton').nth(3).click();
  await page.getByRole('spinbutton').nth(2).click();
  await page.getByRole('spinbutton').nth(2).fill('1');
  await page.getByRole('spinbutton').nth(3).click();
  await page.getByRole('spinbutton').nth(3).fill('1');
  await page.locator('[id=":r76:"]').click();
  await page.locator('[id=":r76:"]').fill('2');
  await page.locator('[id=":r77:"]').click();
  await page.locator('[id=":r77:"]').fill('2');
  await page.locator('[id=":r7c:"]').click();
  await page.locator('[id=":r7c:"]').fill('3');
  await page.locator('[id=":r7d:"]').click();
  await page.locator('[id=":r7c:"]').fill('33');
  await page.locator('[id=":r7c:"]').click();
  await page.locator('[id=":r7c:"]').fill('3');
  await page.locator('[id=":r7d:"]').click();
  await page.locator('[id=":r7d:"]').fill('3');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.locator('form').getByRole('button', { name: 'Add Row' }).click();
  await page.locator('form').getByRole('button', { name: 'Add Row' }).click();
  await page.locator('#system-alias-select-0').click();
  await page.getByRole('option', { name: 'Open' }).click();
  await page.getByRole('combobox', { name: 'System Alias', exact: true }).click();
  await page.getByRole('option', { name: 'Closed' }).click();
  await page.getByRole('row', { name: 'System Alias Open Remove Row' }).getByRole('textbox').click();
  await page.getByRole('combobox', { name: 'System Alias Closed' }).press('Tab');
  await page.getByRole('row', { name: 'System Alias Open Remove Row' }).getByRole('textbox').press('CapsLock');
  await page.getByRole('row', { name: 'System Alias Open Remove Row' }).getByRole('textbox').fill('OPEN');
  await page.getByRole('row', { name: 'System Alias Closed Remove Row' }).getByRole('textbox').click();
  await page.getByRole('row', { name: 'System Alias Closed Remove Row' }).getByRole('textbox').fill('CLOSED');
  await page.getByRole('button', { name: 'Add Row' }).first().click();
  await page.getByRole('button', { name: 'Add Row' }).first().click();
  await page.getByRole('button', { name: 'Add Row' }).first().click();
  await page.getByRole('combobox').first().click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByRole('combobox').nth(3).click();
  await page.getByRole('option', { name: 'NA' }).click();
  await page.getByText('Select').click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.locator('tr').filter({ hasText: 'YesYESNO' }).getByPlaceholder('Compliance').click();
  await page.locator('tr').filter({ hasText: 'YesYESNO' }).getByPlaceholder('Compliance').fill('YES');
  await page.locator('tr').filter({ hasText: 'NAYESNO' }).getByPlaceholder('Compliance').click();
  await page.locator('tr').filter({ hasText: 'NAYESNO' }).getByPlaceholder('Compliance').fill('NA');
  await page.getByRole('row', { name: 'Delete Row #000000 Add Row' }).getByPlaceholder('Compliance').click();
  await page.getByRole('row', { name: 'Delete Row #000000 Add Row' }).getByPlaceholder('Compliance').fill('NO');
  await page.getByRole('row', { name: 'Delete Row YES #000000 Add Row' }).getByLabel('NO').check();
  await page.getByRole('row', { name: 'Delete Row NA #000000 Add Row' }).getByLabel('NO').check();
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByLabel('YES').check();
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByLabel('Add Row').click();
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByLabel('Add Row').click();
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByLabel('Add Row').click();
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByLabel('Add Row').click();
  await page.getByRole('combobox').nth(1).click();
  await page.getByRole('option', { name: '0' }).click();
  await page.getByRole('combobox').nth(1).click();
  await page.getByRole('option', { name: '0' }).click();
  await page.getByRole('combobox').nth(2).click();
  await page.getByRole('option', { name: '0' }).click();
  await page.getByRole('combobox').nth(4).click();
  await page.getByRole('option', { name: '0' }).click();
  await page.getByRole('combobox').nth(5).click();
  await page.getByRole('option', { name: '0' }).click();
  await page.getByRole('row', { name: 'Delete Row YES 0.00 100.00 #' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: 'Delete Row YES 0.00 100.00 #' }).locator('input[type="color"]').fill('#76f254');
  await page.getByRole('cell', { name: '#' }).nth(2).click();
  await page.getByRole('row', { name: 'Delete Row NA 0.00 100.00 #' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: 'Delete Row NA 0.00 100.00 #' }).locator('input[type="color"]').fill('#79e2d5');
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByPlaceholder('Sub Answer').click();
  await page.getByRole('row', { name: 'Delete Row NO #000000 Add Row' }).getByPlaceholder('Sub Answer').fill('LOW');
  await page.getByRole('textbox', { name: 'Sub Answer' }).nth(3).click();
  await page.getByRole('textbox', { name: 'Sub Answer' }).nth(3).fill('MEDIUM');
  await page.getByRole('textbox', { name: 'Sub Answer' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Sub Answer' }).nth(4).fill('HIGH');
  await page.getByRole('textbox', { name: 'Sub Answer' }).nth(5).click();
  await page.getByRole('textbox', { name: 'Sub Answer' }).nth(5).fill('VERY HIGH');
  await page.locator('[id=":r9m:"]').click();
  await page.locator('[id=":r9m:"]').fill('EXTREMELY HIGH');
  await page.locator('tr:nth-child(3) > td:nth-child(6) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click();
  await page.getByRole('option', { name: '0' }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click();
  await page.getByRole('option', { name: '1' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(6) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click();
  await page.getByRole('option', { name: '2' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(7) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click();
  await page.getByRole('option', { name: '2' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(6) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click();
  await page.getByRole('option', { name: '3' }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(7) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click();
  await page.getByRole('option', { name: '4' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(6) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click();
  await page.getByRole('option', { name: '5' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(7) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click();
  await page.getByRole('option', { name: '8' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(6) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click();
  await page.getByRole('option', { name: '8' }).click();
  await page.getByText('8').nth(1).click();
  await page.getByRole('option', { name: '9' }).click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click();
  await page.getByRole('option', { name: '9' }).click();
  await page.getByRole('row', { name: 'Delete Row NO LOW 11.11 88.89' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: 'Delete Row NO LOW 11.11 88.89' }).locator('input[type="color"]').fill('#d09e58');
  await page.getByRole('cell', { name: '#000000' }).first().click();
  await page.getByRole('cell', { name: '#000000' }).first().click();
  await page.getByRole('cell', { name: '#000000' }).first().click();
  await page.getByRole('row', { name: 'MEDIUM 22.22 77.78 #000000' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: 'MEDIUM 22.22 77.78 #000000' }).locator('input[type="color"]').fill('#708dbd');
  await page.getByRole('cell', { name: '#000000' }).nth(1).click();
  await page.getByRole('row', { name: 'HIGH 44.44 55.56 #000000' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: 'HIGH 44.44 55.56 #000000' }).locator('input[type="color"]').fill('#68acb1');
  await page.getByRole('cell', { name: '#000000' }).nth(1).click();
  await page.getByRole('row', { name: 'VERY HIGH 88.89 11.11 #000000' }).locator('input[type="color"]').fill('#9179af');
  await page.getByRole('cell', { name: '#000000' }).first().click();
  await page.locator('tr:nth-child(7) > td:nth-child(10) > .MuiTableCell-root > .MuiBox-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(10) > .MuiTableCell-root > .MuiBox-root').fill('#a3aa6e');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('button', { name: 'Add Row' }).click();
  await page.getByRole('button', { name: 'Add Row' }).click();
  await page.getByRole('button', { name: 'Add Row' }).click();
  await page.getByRole('combobox', { name: 'System Alias' }).first().click();
  await page.getByRole('option', { name: 'Open' }).click();
  await page.getByRole('option', { name: 'Open' }).click();
  await page.locator('td').filter({ hasText: 'System AliasSystem Alias *' }).getByLabel('System Alias').click();
  await page.getByRole('option', { name: 'Completed' }).click();
  await page.getByRole('combobox', { name: 'System Alias' }).nth(1).click();
  await page.getByRole('option', { name: 'Wip' }).click();
  await page.locator('tr').filter({ hasText: 'System AliasOpenSystem Alias *' }).getByRole('textbox').click();
  await page.locator('tr').filter({ hasText: 'System AliasOpenSystem Alias *' }).getByRole('textbox').fill('OPEN');
  await page.locator('tr').filter({ hasText: 'System AliasWipSystem Alias *' }).getByRole('textbox').click();
  await page.locator('tr').filter({ hasText: 'System AliasWipSystem Alias *' }).getByRole('textbox').fill('WIP');
  await page.getByRole('row', { name: 'System Alias Remove Row', exact: true }).getByRole('textbox').click();
  await page.getByRole('row', { name: 'System Alias Remove Row', exact: true }).getByRole('textbox').fill('COMPLETED');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('paragraph').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('paragraph').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('spinbutton').first().fill('0');
  await page.getByRole('spinbutton').nth(1).click();
  await page.getByRole('spinbutton').nth(1).fill('50');
  await page.getByRole('spinbutton').nth(2).click();
  await page.getByRole('spinbutton').nth(2).fill('51');
  await page.getByRole('spinbutton').nth(3).click();
  await page.getByRole('spinbutton').nth(3).fill('60');
  await page.getByRole('spinbutton').nth(4).click();
  await page.getByRole('spinbutton').nth(4).fill('61');
  await page.getByRole('spinbutton').nth(5).click();
  await page.getByRole('spinbutton').nth(5).fill('70');
  await page.locator('[id=":rb6:"]').click();
  await page.locator('[id=":rb6:"]').fill('71');
  await page.locator('[id=":rb7:"]').click();
  await page.locator('[id=":rb7:"]').fill('85');
  await page.locator('[id=":rbe:"]').click();
  await page.locator('[id=":rbe:"]').fill('86');
  await page.locator('[id=":rbf:"]').click();
  await page.locator('[id=":rbe:"]').fill('86100');
  await page.locator('[id=":rbe:"]').click();
  await page.locator('[id=":rbe:"]').fill('86');
  await page.locator('[id=":rbf:"]').click();
  await page.locator('[id=":rbf:"]').fill('100');
  await page.locator('[id=":rbg:"]').click();
  await page.locator('[id=":rbg:"]').fill('A');
  await page.locator('[id=":rb8:"]').click();
  await page.locator('[id=":rb8:"]').fill('B');
  await page.locator('[id=":rb0:"]').click();
  await page.locator('[id=":rb8:"]').fill('BC');
  await page.locator('[id=":rb0:"]').fill('C');
  await page.locator('[id=":rb8:"]').click();
  await page.locator('[id=":rb8:"]').fill('B');
  await page.locator('tr:nth-child(2) > td:nth-child(3)').click();
  await page.getByRole('textbox').nth(4).fill('D');
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('E');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('UNSATISFACTORY RUN');
  await page.locator('tr:nth-child(2) > td:nth-child(4)').click();
  await page.getByRole('textbox').nth(5).fill('SATISFACTORY RUN');
  await page.locator('[id=":rb1:"]').click();
  await page.locator('[id=":rb1:"]').fill('FAIRLY WELL RUN');
  await page.locator('[id=":rb9:"]').click();
  await page.locator('[id=":rb1:"]').fill('FAIRLY WELL RUNWE');
  await page.locator('[id=":rb9:"]').fill('LL');
  await page.locator('[id=":rb1:"]').click();
  await page.locator('[id=":rb1:"]').fill('FAIRLY WELL RUN');
  await page.locator('[id=":rb9:"]').click();
  await page.locator('[id=":rb9:"]').fill('WELL RUN');
  await page.locator('[id=":rbh:"]').click();
  await page.locator('[id=":rb9:"]').fill('WELL RUNE');
  await page.locator('[id=":rbh:"]').fill('EXCELLENT RUN');
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('EXTREMELY HIGH RISK');
  await page.locator('input[type="text"]').nth(5).click();
  await page.locator('input[type="text"]').nth(5).fill('VERY HIGH RISK');
  await page.locator('[id=":rb2:"]').click();
  await page.locator('[id=":rb2:"]').fill('HIGH RISK');
  await page.locator('[id=":rba:"]').click();
  await page.locator('[id=":rb2:"]').fill('HIGH RISKM');
  await page.locator('[id=":rba:"]').fill('MEDIUM RISK');
  await page.locator('[id=":rb2:"]').click();
  await page.locator('[id=":rb2:"]').fill('HIGH RISK');
  await page.locator('[id=":rbi:"]').click();
  await page.locator('[id=":rbi:"]').fill('LOW RISK');
  await page.locator('td:nth-child(7)').first().click();
  await page.getByRole('option', { name: 'Monthly' }).click();
  await page.getByRole('option', { name: 'Monthly' }).click();
  await page.getByRole('row', { name: '61 70 C FAIRLY WELL RUN HIGH RISK #' }).getByRole('combobox').click();
  await page.getByRole('option', { name: 'Quarterly' }).click();
  await page.getByRole('row', { name: '85 B WELL RUNE MEDIUM RISK #000000' }).getByRole('combobox').click();
  await page.getByRole('option', { name: 'Half Yearly' }).click();
  await page.getByRole('row', { name: '86 100 A EXCELLENT RUN LOW' }).getByRole('combobox').click();
  await page.getByRole('option', { name: 'Yearly', exact: true }).click();
  await page.getByRole('row', { name: '0 50 E UNSATISFACTORY RUN' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: '0 50 E UNSATISFACTORY RUN' }).locator('input[type="color"]').fill('#da3434');
  await page.getByRole('cell', { name: '#' }).nth(1).click();
  await page.getByRole('row', { name: '51 60 D SATISFACTORY RUN VERY' }).locator('input[type="color"]').fill('#d26097');
  await page.getByRole('row', { name: '61 70 C FAIRLY WELL RUN HIGH RISK #' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: '61 70 C FAIRLY WELL RUN HIGH RISK #' }).locator('input[type="color"]').fill('#d68a4c');
  await page.locator('div').filter({ hasText: 'Finish' }).nth(3).click();
  await page.getByRole('row', { name: '85 B WELL RUNE MEDIUM RISK #000000' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: '85 B WELL RUNE MEDIUM RISK #000000' }).locator('input[type="color"]').fill('#5fa597');
  await page.locator('[id=":rb9:"]').click();
  await page.locator('[id=":rb9:"]').fill('WELL RUN');
  await page.getByRole('cell', { name: '#000000' }).locator('input[type="color"]').click();
  await page.getByRole('cell', { name: '#000000' }).locator('input[type="color"]').fill('#8fcedb');
  await page.locator('html').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Finish' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('menuitem', { name: 'Admin' }).click();
    await page.getByRole('menuitem', { name: 'Audit Type' }).click();
    await page.getByRole('menuitem', { name: 'View List' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company1' }).click();
    // -------------Map Audit Type to Area-----------------    
    await page.getByRole('menuitem', { name: 'Admin' }).click();
    await page.getByRole('menuitem', { name: 'Audit Type' }).click();
    await page.getByRole('menuitem', { name: 'Map AuditType To Area' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company1' }).click();
    await page.getByRole('combobox').nth(1).click();
    await page.getByRole('option', { name: 'C1 RBIA' }).click();
    await page.getByRole('checkbox', { name: 'Mumbai Ho' }).check();
    await page.getByRole('button', { name: 'move selected right' }).first().click();
    await page.getByRole('checkbox', { name: 'C1_RBIA_BA1' }).check();
    await page.getByRole('checkbox', { name: 'C1_RBIA_BA2' }).check();
    await page.getByRole('checkbox', { name: 'C1_RBIA_BA3' }).check();
    await page.getByRole('button', { name: 'move selected left' }).nth(1).click();
    await page.getByRole('button', { name: 'Map' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company1' }).click();
    await page.getByRole('combobox').nth(1).click();
    await page.getByRole('option', { name: 'C1 RBIA' }).click();
    await page.getByRole('checkbox', { name: 'Pune Branch' }).check();
    await page.getByRole('button', { name: 'move selected right' }).first().click();
    await page.getByRole('checkbox', { name: 'C1_RBIA_BA1' }).check();
    await page.getByRole('checkbox', { name: 'C1_RBIA_BA2' }).check();
    await page.getByRole('button', { name: 'move selected left' }).nth(1).click();
    await page.getByRole('button', { name: 'Map' }).click();
    // -------------Create Workflow-----------------
    await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Workflow', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.locator('#mui-component-select-auditTypeId').click();
  await page.getByRole('option', { name: 'C1 RBIA' }).click();
  await page.getByRole('textbox', { name: 'Workflow Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Name' }).fill('M');
  await page.getByRole('textbox', { name: 'Workflow Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Workflow Name' }).fill('Maker Checker (');
  await page.getByRole('textbox', { name: 'Workflow Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Workflow Name' }).fill('Maker Checker (C1RBIA)');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
    // -------------Create Workflow Stages-----------------
    await page.getByRole('menuitem', { name: 'Admin' }).click();
    await page.getByRole('menuitem', { name: 'Workflow', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Admin' }).click();
    await page.getByRole('menuitem', { name: 'Workflow Stages' }).click();
    await page.getByRole('menuitem', { name: 'Create' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company1' }).click();
    await page.getByLabel('', { exact: true }).click();
    await page.getByRole('option', { name: 'C1 RBIA' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Planned');
    await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
    await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Created');
    await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
    await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Document Upload');
    await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
    await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit In Progress');
    await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
    await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Completed');
    await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
    await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Compliance In Progress');
    await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
    await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Compliance Verification');
    await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
    await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
    await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Closed');
    await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
    await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    // -------------Assign Workflow-----------------
    await page.getByRole('link', { name: 'Assign Sequence to Workflow' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company1' }).click();
    await page.getByRole('combobox', { name: 'Stage Workflow' }).click();
    await page.getByRole('option', { name: 'Maker Checker (C1RBIA)' }).click();
    await page.getByRole('option', { name: 'Maker Checker (C1RBIA)' }).click();
    await page.getByRole('option', { name: 'Audit Planned' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('1');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
    await page.getByRole('option', { name: 'Audit Created' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('2');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
    await page.getByRole('option', { name: 'Document Upload' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('3');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
    await page.getByRole('option', { name: 'Audit In Progress' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('4');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
    await page.getByRole('option', { name: 'Audit Completed' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('5');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
    await page.getByRole('option', { name: 'Compliance In Progress' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('6');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
    await page.getByRole('option', { name: 'Compliance Verification' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('7');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
    await page.getByRole('option', { name: 'Audit Closed' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
    await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('8');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByText('Note: After assigning').click();
    // -------------Manage Workflow Access-----------------
    await page.getByRole('link', { name: 'Manage Workflow Access' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company1' }).click();
    await page.getByRole('combobox', { name: 'Audit Type' }).click();
  await page.getByRole('option', { name: 'C1 RBIA' }).click();
  await page.getByRole('combobox', { name: 'Role' }).click();
  await page.getByRole('option', { name: 'C1OrgAdmin' }).click();
  await page.getByTestId('CheckBoxOutlineBlankIcon').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(3) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(11) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.getByTestId('CheckBoxOutlineBlankIcon').nth(2).click();
  await page.locator('tr:nth-child(2) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(6)').click();
  await page.locator('tr:nth-child(6) > td:nth-child(6)').click();
  await page.locator('tr:nth-child(7) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(9) > .MuiSvgIcon-root > path').first().click();
  await page.locator('tr:nth-child(5) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(9) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(11) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(12) > .MuiSvgIcon-root > path').first().click();
  await page.locator('tr:nth-child(6) > td:nth-child(12) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(12) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(12) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(12) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(12) > .MuiSvgIcon-root > path').click();
  await page.locator('td:nth-child(15) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(15)').click();
  await page.locator('tr:nth-child(9) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(18) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(20) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Role C1OrgAdmin' }).click();
  await page.getByRole('option', { name: 'C1Auditor', exact: true }).click();
  await page.locator('tr:nth-child(3) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(3) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(9) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(20) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(4) > td:nth-child(20) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(3) > td:nth-child(15)').click();
  await page.locator('tr:nth-child(4) > td:nth-child(15) > .MuiSvgIcon-root > path').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Role C1Auditor' }).click();
  await page.getByRole('option', { name: 'C1Auditee', exact: true }).click();
  await page.locator('tr:nth-child(5) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(2) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(5) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(6) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('div').filter({ hasText: 'OrganizationOrganizationAudit' }).nth(5).click();
  await page.getByRole('combobox', { name: 'Role C1Auditee' }).click();
  await page.getByRole('option', { name: 'C1AuditeeReviewer' }).click();
  await page.getByTestId('CheckBoxOutlineBlankIcon').nth(4).click();
  await page.locator('tr:nth-child(2) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(8)').click();
  await page.locator('tr:nth-child(9) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(11) > .MuiSvgIcon-root > path').first().click();
  await page.locator('tr:nth-child(4) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(11)').click();
  await page.locator('tr:nth-child(9) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(12) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(8) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Role C1AuditeeReviewer' }).click();
  await page.getByRole('option', { name: 'C1AuditorReviewer' }).click();
  await page.locator('td:nth-child(8) > .MuiSvgIcon-root > path').first().click();
  await page.locator('tr:nth-child(6) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(8) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(11) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(7) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(8) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(9) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(11) > td:nth-child(11) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(9) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(9) > .MuiSvgIcon-root > path').click();
  await page.locator('tr:nth-child(5) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(6) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(10) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.getByRole('button', { name: 'Submit' }).click();
    // -------------Define Workflow-----------------
    await page.getByRole('link', { name: 'Define Workflow' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company1' }).click();
    await page.getByRole('combobox', { name: 'Audit Type' }).click();
    await page.getByRole('option', { name: 'C1 RBIA' }).click();
    await page.getByRole('combobox', { name: 'Workflow Stages' }).first().click();
    await page.getByRole('option', { name: 'Audit In Progress' }).click();
    await page.getByRole('checkbox', { name: 'Set Audit Actual Start Date' }).check();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.locator('form').getByText('Audit In Progress').click();
    await page.getByRole('option', { name: 'Audit Completed' }).click();
    await page.getByRole('checkbox', { name: 'Generate Audit Complete Report' }).check();
    await page.getByRole('checkbox', { name: 'Set Audit Actual Finish Date' }).check();
    await page.getByRole('checkbox', { name: 'Generate Score' }).check();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('checkbox', { name: 'Set Udin No' }).check();
    await page.getByRole('checkbox', { name: 'Set Udin No' }).press('ScrollLock');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.locator('form').getByText('Audit Completed').click();
    await page.getByRole('option', { name: 'Audit Closed' }).click();
    await page.getByRole('checkbox', { name: 'Set Audit Closed Date' }).check();
    await page.getByRole('checkbox', { name: 'Generate Audit Closed Report' }).check();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.locator('form').getByText('Audit Closed', { exact: true }).click();
    await page.getByRole('option', { name: 'Compliance Verification' }).click();
    await page.getByRole('combobox', { name: 'Select Fields' }).click();
    await page.getByRole('option', { name: 'Control Effectiveness' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    // -------------Create Audit-----------------
    await page.getByRole('menuitem', { name: 'Audit' }).click();
    await page.getByRole('menuitem', { name: 'Audit Annual Plan' }).click();
    await page.getByRole('combobox', { name: 'Audit Type' }).click();
    await page.getByRole('option', { name: 'C1 Concurrent Simple' }).click();
    await page.getByRole('combobox', { name: 'Frequency' }).click();
    await page.getByRole('option', { name: 'By Audit Type' }).click();
    await page.getByRole('combobox', { name: 'Audit Plan for' }).click();
    await page.getByRole('option', { name: 'Calendar Year' }).click();
    await page.getByRole('button', { name: 'Generate', exact: true }).click();
    await page.getByRole('combobox', { name: 'Months of 2025' }).click();
    await page.getByRole('option', { name: 'Jan' }).click();
    await page.getByRole('button', { name: 'Generate Schedule' }).click();
    await page.getByRole('button', { name: 'Initiate Audit' }).click();
    await page.getByLabel('', { exact: true }).click();
    await page.getByRole('option', { name: 'Audit Created' }).click();
    await page.getByRole('textbox', { name: 'Audit Name' }).click();
    await page.getByRole('textbox', { name: 'Audit Name' }).fill('C1 RBIA Jan 2025');
    await page.getByRole('textbox', { name: 'Planned Start Date' }).fill('2025-01-08');
    await page.getByRole('textbox', { name: 'Planned Finish Date' }).fill('2025-01-08');
    await page.getByRole('textbox', { name: 'Planned Start Time' }).click();
    await page.getByRole('textbox', { name: 'Planned Start Time' }).fill('10:00');
    await page.getByRole('textbox', { name: 'Planned Finish Time' }).click();
    await page.getByRole('textbox', { name: 'Planned Finish Time' }).fill('17:00');
    await page.getByRole('textbox', { name: 'Audit Period From' }).fill('2024-12-01');
    await page.getByRole('textbox', { name: 'Audit Period To' }).fill('2024-12-31');
    await page.getByRole('textbox', { name: 'Audit Scope' }).click();
    await page.getByRole('textbox', { name: 'Audit Scope' }).fill('Scope');
    await page.getByRole('textbox', { name: 'Audit Objective' }).click();
    await page.getByRole('textbox', { name: 'Audit Objective' }).fill('Objective');
    await page.getByRole('button', { name: 'Add Users +' }).click();
    await page.getByRole('button', { name: 'Add Users +' }).click();
    await page.getByRole('button', { name: 'Add Users +' }).click();
    await page.getByRole('button', { name: 'Add Users +' }).click();
    await page.getByRole('button', { name: 'Add Users +' }).click();
    await page.getByRole('button', { name: 'Remove' }).nth(4).click();
    await page.getByRole('button', { name: 'Remove' }).nth(2).click();
    await page.getByRole('combobox', { name: 'Select User' }).first().click();
    await page.getByRole('option', { name: 'c1companyadmin-C1OrgAdmin' }).click();
    await page.getByRole('combobox', { name: 'Select User' }).nth(1).click();
    await page.getByRole('option', { name: 'c1companyauditee-C1Auditee' }).click();
    await page.getByRole('combobox', { name: 'Select User' }).nth(2).click();
    await page.getByRole('option', { name: 'c1companyauditor-C1Auditor' }).click();
    await page.getByRole('combobox', { name: 'Assign Audit Level Role' }).first().click();
    await page.getByRole('checkbox').uncheck();
    await page.getByText('C1OrgAdmin', { exact: true }).click();
    await page.getByRole('combobox', { name: 'Assign Audit Level Role' }).nth(1).click();
    await page.getByRole('checkbox').uncheck();
    await page.getByText('C1Auditee', { exact: true }).click();
    await page.getByRole('combobox', { name: 'Assign Audit Level Role' }).nth(2).click();
    await page.getByRole('checkbox').uncheck();
    await page.locator('#menu-').getByText('default').click();
    await page.getByRole('checkbox', { name: 'Is Lead Auditor?' }).check();
    await page.getByRole('button', { name: 'Create' }).click();
    await page.getByRole('menuitem', { name: 'Audit' }).click();
    await page.getByRole('menuitem', { name: 'List View' }).click();
    
});