import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {

  await page.goto('http://localhost:8080/realms/aspl-realm/protocol/openid-connect/auth?response_type=code&client_id=aspl-open-id&redirect_uri=http%3A%2F%2Flocalhost%3A3000&code_challenge=UW0Eb3jCQySRSm6IYatJ1DfOG3EhgglgD-rdEW9uM90&code_challenge_method=S256&scope=profile+openid&state=customLoginState');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('vishalp');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div').filter({ hasText: 'AMS' }).nth(4).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Organization' }).click();
  await page.getByRole('menuitem', { name: 'Create Organization' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Organization' }).click();
  await page.getByRole('menuitem', { name: 'Create Domain' }).click();
  await page.getByRole('textbox', { name: 'Domain Name' }).click();
  await page.getByRole('textbox', { name: 'Domain Name' }).fill('Banking');
  await page.getByRole('combobox', { name: 'Domain Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Is Data Integration Required?' }).check();
  await page.getByRole('checkbox', { name: 'Is Data Integration Required?' }).press('ScrollLock');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).getByTestId('ArrowDropDownIcon').click();
  await page.getByRole('menuitem', { name: 'Organization' }).click();
  await page.getByRole('menuitem', { name: 'View Domain' }).click();
  // --------------------- CREATE ORGANIZATION ---------------------
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Organization' }).click();
  await page.getByRole('menuitem', { name: 'Create Organization' }).click();
  await page.getByRole('textbox', { name: 'Organization Name' }).fill('Company1');
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Category' }).fill('Urban Cooperative Bank');
  await page.getByRole('combobox', { name: 'Organization Domain' }).click();
  await page.getByRole('option', { name: 'Banking' }).click();
  await page.getByRole('button', { name: 'Organization Logo' }).setInputFiles('logo.png');
  await page.getByRole('button', { name: 'Save' }).click();
  // --------------------- CREATE LOCATION ---------------------
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Location' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('textbox', { name: 'Location Name' }).fill('C1 Mumbai HO');
  await page.getByRole('combobox', { name: 'Country' }).click();
  await page.getByRole('option', { name: 'India' }).click();
  await page.getByRole('combobox', { name: 'State' }).click();
  await page.getByRole('option', { name: 'Maharashtra' }).click();
  await page.getByRole('combobox', { name: 'City' }).click();
  await page.getByRole('option', { name: 'Mumbai' }).click();
  await page.getByRole('textbox', { name: 'Address' }).fill('Mumbai');
  await page.getByRole('textbox', { name: 'Branch Code' }).fill('MUMHO001');
  await page.getByRole('spinbutton', { name: 'Pincode' }).fill('400001');
  await page.getByRole('combobox', { name: 'Location Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Location' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('textbox', { name: 'Location Name' }).fill('C1 Pune Branch');
  await page.getByRole('combobox', { name: 'Country' }).click();
  await page.getByRole('option', { name: 'India' }).click();
  await page.getByRole('combobox', { name: 'State' }).click();
  await page.getByRole('option', { name: 'Maharashtra' }).click();
  await page.getByRole('combobox', { name: 'City' }).click();
  await page.getByRole('option', { name: 'Pune' }).click();
  await page.getByRole('textbox', { name: 'Address' }).fill('Pune, Maharashtra');
  await page.getByRole('textbox', { name: 'Branch Code' }).fill('PUNBR001');
  await page.getByRole('spinbutton', { name: 'Pincode' }).fill('411001');
  await page.getByRole('combobox', { name: 'Location Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  // --------------------- CREATE DEPARTMENT ---------------------
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Department' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Location' }).click();
  await page.getByRole('option', { name: 'C1 Mumbai HO' }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).fill('C1DEPTA');
  await page.getByRole('combobox', { name: 'Department Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Location' }).click();
  await page.getByRole('option', { name: 'C1 Mumbai HO' }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).fill('C1DEPTB');
  await page.getByRole('combobox', { name: 'Department Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Location' }).click();
  await page.getByRole('option', { name: 'C1 Pune Branch' }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).fill('C1DEPTC');
  await page.getByRole('combobox', { name: 'Department Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Location' }).click();
  await page.getByRole('option', { name: 'C1 Pune Branch' }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).fill('C1DEPTD');
  await page.getByRole('combobox', { name: 'Department Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  // --------------------- CREATE ROLES ---------------------
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Role' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C1OrgAdmin');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Org admin role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Admin' }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Role' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C1Auditor');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Auditor role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Auditor', exact: true }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Role' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C1AuditorReviewer');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Auditor Reviewer role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Auditor_Reviewer' }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Role' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C1Auditee');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Auditee role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Auditee', exact: true }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Role' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C1AuditeeReviewer');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Auditee Reviewer role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Auditee_Reviewer' }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  // --------------------- CREATE USERS ---------------------
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c1admin');
  await page.getByRole('textbox', { name: 'Password:' }).fill('Vish@12345');
  await page.getByRole('textbox', { name: 'Email:' }).fill('c1admin@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).fill('C1');
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('ADMIN (MUMBAI HO)');
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 23232-32323');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'C1OrgAdmin' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'MUMBAI HO' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'DEPTA' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'View List', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c1auditor1');
  await page.getByRole('textbox', { name: 'Password:' }).fill('Vish@12345');
  await page.getByRole('textbox', { name: 'Email:' }).fill('c1auditor1@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).fill('C1 AUDITOR1');
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('(MUMBAI HO) DEPTA');
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 32323-43454');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'C1Auditor' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'MUMBAI HO' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'DEPTA' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'View List', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c1auditorr');
  await page.getByRole('textbox', { name: 'Password:' }).fill('Vish@1234');
  await page.getByRole('textbox', { name: 'Email:' }).fill('c1auditorr@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).fill('C1 AUDITORR');
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('(MUMBAI HO) DEPTB');
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 87656-54543');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'C1AuditorReviewer' }).click();
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'MUMBAI HO' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'DEPTB' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'View List', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c1auditee1');
  await page.getByRole('textbox', { name: 'Password:' }).fill('Vish@12345');
  await page.getByRole('textbox', { name: 'Email:' }).fill('c1auditee1@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).fill('C1 AUDITEE1');
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('(MUMBAI HO) DEPTA');
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 54545-45454');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'C1Auditee' }).click();
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'MUMBAI HO' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'DEPTA' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).getByTestId('ArrowDropDownIcon').click();
  await page.getByRole('menuitem', { name: 'User' }).getByTestId('ArrowRightIcon').click();
  await page.getByRole('menuitem', { name: 'View List' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c1auditeer');
  await page.getByRole('textbox', { name: 'Password:' }).fill('Vish@1234');
  await page.getByRole('textbox', { name: 'Email:' }).fill('auditeereviewer@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).fill('C1 AUDITEER');
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('(MUMBAI HO) DEPTB');
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 67656-76784');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'C1AuditeeReviewer' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'DEPTB' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'View List' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('aspladmin');
  await page.getByRole('textbox', { name: 'Password:' }).fill('Vish@12345');
  await page.getByRole('textbox', { name: 'Email:' }).fill('aspladmin@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).fill('ASPL');
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('ADMIN');
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 99999-88888');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company1' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'ASPLAdmin' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();

});