import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {

    await page.goto('http://localhost:8080/realms/aspl-realm/protocol/openid-connect/auth?response_type=code&client_id=aspl-open-id&redirect_uri=http%3A%2F%2Flocalhost%3A3000&code_challenge=UW0Eb3jCQySRSm6IYatJ1DfOG3EhgglgD-rdEW9uM90&code_challenge_method=S256&scope=profile+openid&state=customLoginState');
    await page.getByRole('textbox', { name: 'Username or email' }).click();
    await page.getByRole('textbox', { name: 'Username or email' }).fill('vishalp');
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('12345');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.locator('div').filter({ hasText: 'AMS' }).nth(4).click();
    await page.getByRole('menuitem', { name: 'Admin' }).getByTestId('ArrowDropDownIcon').click();
    await page.getByRole('menuitem', { name: 'Loan Masters' }).click();
    await page.getByRole('menuitem', { name: 'Loan Type' }).click();
    await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company 1' }).click();
    await page.getByRole('textbox', { name: 'Loan Type' }).fill('C1_LT1');
    await page.getByRole('combobox', { name: 'Loan Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('textbox', { name: 'Loan Type' }).fill('C1_LT2');
    await page.getByRole('combobox', { name: 'Loan Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('menuitem', { name: 'Loan Masters' }).click();
    await page.getByRole('menuitem', { name: 'Loan Subtype' }).click();
    await page.getByRole('menuitem', { name: 'Create' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company 1' }).click();
    await page.getByRole('combobox', { name: 'Select Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1' }).click();
    await page.getByRole('textbox', { name: 'Loan Sub Type' }).fill('C1_LT1_ST1');
    await page.getByRole('combobox', { name: 'Loan Sub Type Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Select Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1' }).click();
    await page.getByRole('textbox', { name: 'Loan Sub Type' }).fill('C1_LT1_ST2');
    await page.getByRole('combobox', { name: 'Loan Sub Type Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Select Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT2' }).click();
    await page.getByRole('textbox', { name: 'Loan Sub Type' }).fill('C1_LT2_ST1');
    await page.getByRole('combobox', { name: 'Loan Sub Type Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('menuitem', { name: 'Loan Masters' }).click();
    await page.getByRole('menuitem', { name: 'Loan Question' }).click();
    await page.getByRole('menuitem', { name: 'Create' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company 1' }).click();
    await page.getByRole('combobox', { name: 'Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1' }).click();
    await page.getByRole('combobox', { name: 'Loan Sub Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1_ST1' }).click();
    await page.getByRole('textbox', { name: 'Loan Question' }).fill('C1_LT1_ST1_QUESTION1');
    await page.getByRole('combobox', { name: 'Loan Question Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1' }).click();
    await page.getByRole('combobox', { name: 'Loan Sub Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1_ST1' }).click();
    await page.getByRole('textbox', { name: 'Loan Question' }).fill('C1_LT1_ST1_QUESTION2');
    await page.getByRole('combobox', { name: 'Loan Question Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1' }).click();
    await page.getByRole('combobox', { name: 'Loan Sub Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1_ST2' }).click();
    await page.getByRole('textbox', { name: 'Loan Question' }).fill('C1_LT1_ST2_QUESTION1');
    await page.getByRole('combobox', { name: 'Loan Question Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1' }).click();
    await page.getByRole('combobox', { name: 'Loan Sub Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1_ST2' }).click();
    await page.getByRole('textbox', { name: 'Loan Question' }).fill('C1_LT1_ST2_QUESTION2');
    await page.getByRole('combobox', { name: 'Loan Question Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1' }).click();
    await page.getByRole('combobox', { name: 'Loan Sub Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1_ST2' }).click();
    await page.getByRole('textbox', { name: 'Loan Question' }).fill('C1_LT1_ST2_QUESTION3');
    await page.getByRole('combobox', { name: 'Loan Question Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT2' }).click();
    await page.getByRole('combobox', { name: 'Loan Sub Type' }).click();
    await page.getByRole('option', { name: 'C1_LT2_ST1' }).click();
    await page.getByRole('textbox', { name: 'Loan Question' }).fill('C1_LT2_ST1_QUESTION1');
    await page.getByRole('combobox', { name: 'Loan Question Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT2' }).click();
    await page.getByRole('combobox', { name: 'Loan Sub Type' }).click();
    await page.getByRole('option', { name: 'C1_LT2_ST1' }).click();
    await page.getByRole('textbox', { name: 'Loan Question' }).fill('C1_LT2_ST1_QUESTION2');
    await page.getByRole('combobox', { name: 'Loan Question Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('menuitem', { name: 'Loan Masters' }).click();
    await page.getByRole('menuitem', { name: 'Loan Document' }).click();
    await page.getByRole('menuitem', { name: 'Create' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company 1' }).click();
    await page.getByRole('combobox', { name: 'Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1' }).click();
    await page.getByRole('combobox', { name: 'Loan Sub Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1_ST1' }).click();
    await page.getByRole('combobox', { name: 'Loan Question' }).click();
    await page.getByRole('option', { name: 'C1_LT1_ST1_QUESTION2' }).click();
    await page.getByRole('textbox', { name: 'Loan Document Name' }).fill('C1_LT1_ST1_AuditorDocument');
    await page.getByRole('combobox', { name: 'Category' }).click();
    await page.getByRole('option', { name: 'AUDITOR' }).click();
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_LT1_ST1_AuditorDocument.pdf');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1' }).click();
    await page.getByRole('combobox', { name: 'Loan Sub Type' }).click();
    await page.getByRole('option', { name: 'C1_LT1_ST2' }).click();
    await page.getByRole('combobox', { name: 'Loan Question' }).click();
    await page.getByRole('option', { name: 'C1_LT1_ST2_QUESTION2' }).click();
    await page.getByRole('textbox', { name: 'Loan Document Name' }).fill('C1_LT1_ST2_AuditorDocument');
    await page.getByRole('combobox', { name: 'Category' }).click();
    await page.getByRole('option', { name: 'AUDITOR' }).click();
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_LT1_ST2_AuditorDocument.pdf');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Loan Question' }).click();
    await page.getByRole('option', { name: 'C1_LT1_ST2_QUESTION2' }).click();
    await page.getByRole('textbox', { name: 'Loan Document Name' }).fill('C1_LT1_ST2_AuditeeDocument');
    await page.getByRole('combobox', { name: 'Category' }).click();
    await page.getByRole('option', { name: 'AUDITEE' }).click();
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_LT1_ST2_AuditeeDocument.pdf');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Loan Type' }).click();
    await page.getByRole('option', { name: 'C1_LT2' }).click();
    await page.getByRole('combobox', { name: 'Loan Sub Type' }).click();
    await page.getByRole('option', { name: 'C1_LT2_ST1' }).click();
    await page.getByRole('combobox', { name: 'Loan Question' }).click();
    await page.getByRole('option', { name: 'C1_LT2_ST1_QUESTION1' }).click();
    await page.getByRole('textbox', { name: 'Loan Document Name' }).fill('C1_LT2_ST1_AuditorDocument');
    await page.getByRole('combobox', { name: 'Category' }).click();
    await page.getByRole('option', { name: 'AUDITOR' }).click();
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_LT2_ST1_AuditorDocument.pdf');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Loan Question' }).click();
    await page.getByRole('option', { name: 'C1_LT2_ST1_QUESTION2' }).click();
    await page.getByRole('textbox', { name: 'Loan Document Name' }).fill('C1_LT2_ST1_AuditeeDocument1');
    await page.getByRole('combobox', { name: 'Category' }).click();
    await page.getByRole('option', { name: 'AUDITEE' }).click();
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_LT2_ST1_AuditeeDocument1.pdf');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('combobox', { name: 'Loan Question' }).click();
    await page.getByRole('option', { name: 'C1_LT2_ST1_QUESTION2' }).click();
    await page.getByRole('textbox', { name: 'Loan Document Name' }).fill('C1_LT2_ST1_AuditeeDocument2');
    await page.getByRole('combobox', { name: 'Category' }).click();
    await page.getByRole('option', { name: 'AUDITEE' }).click();
    await page.getByRole('combobox', { name: 'Status' }).click();
    await page.getByRole('option', { name: 'Active' }).click();
    await page.getByRole('button', { name: 'Choose File' }).setInputFiles('C1_LT2_ST1_AuditeeDocument2.pdf');
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('menuitem', { name: 'Admin' }).click();
    await page.getByRole('menuitem', { name: 'Audit Type' }).click();
    await page.getByRole('menuitem', { name: 'Loan Masters' }).click();
    await page.getByRole('menuitem', { name: 'Map AuditType To LoanType' }).click();
    await page.getByRole('combobox', { name: 'Organization' }).click();
    await page.getByRole('option', { name: 'Company 1' }).click();
    await page.getByRole('combobox', { name: 'Select Audit Type' }).click();
    await page.getByRole('option', { name: 'C1 Concurrent Simple' }).click();
    await page.getByRole('combobox', { name: 'Select Loantype' }).click();
    await page.getByRole('option', { name: 'C1_LT1' }).click();
    await page.getByRole('option', { name: 'C1_LT2' }).click();
    await page.getByRole('button', { name: 'Map' }).click();
    
});