import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {

await page.goto('http://localhost:8080/realms/aspl-realm/protocol/openid-connect/auth?response_type=code&client_id=aspl-open-id&redirect_uri=http%3A%2F%2Flocalhost%3A3000&code_challenge=UW0Eb3jCQySRSm6IYatJ1DfOG3EhgglgD-rdEW9uM90&code_challenge_method=S256&scope=profile+openid&state=customLoginState');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('vishalp');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div').filter({ hasText: 'AMS' }).nth(4).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Organization' }).click();
  await page.getByRole('menuitem', { name: 'Create Organization' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Organization' }).click();
  await page.getByRole('menuitem', { name: 'Create Domain' }).click();
  await page.getByRole('textbox', { name: 'Domain Name' }).click();
  await page.getByRole('textbox', { name: 'Domain Name' }).fill('Banking');
  await page.getByRole('combobox', { name: 'Domain Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Is Data Integration Required?' }).check();
  await page.getByRole('checkbox', { name: 'Is Data Integration Required?' }).press('ScrollLock');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).getByTestId('ArrowDropDownIcon').click();
  await page.getByRole('menuitem', { name: 'Organization' }).click();
  await page.getByRole('menuitem', { name: 'View Domain' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Organization' }).click();
  await page.getByRole('menuitem', { name: 'Create Organization' }).click();
  await page.getByRole('textbox', { name: 'Organization Name' }).click();
  await page.getByRole('textbox', { name: 'Organization Name' }).fill('Company 2');
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Category' }).click();
  await page.getByRole('textbox', { name: 'Category' }).fill('Private');
  await page.getByRole('combobox', { name: 'Organization Domain' }).click();
  await page.getByRole('option', { name: 'Banking' }).click();
  await page.getByRole('button', { name: 'Organization Logo' }).press('ScrollLock');
  await page.getByRole('button', { name: 'Organization Logo' }).setInputFiles('logo (2).png');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).getByTestId('ArrowDropDownIcon').click();
  await page.getByRole('menuitem', { name: 'Organization' }).click();
  await page.locator('.MuiPopover-root.MuiModal-root.css-1t4ug28-MuiModal-root-MuiPopover-root > .MuiBackdrop-root').click();
  await page.getByRole('menuitem', { name: 'Location' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company' }).click();
  await page.getByRole('textbox', { name: 'Location Name' }).click();
  await page.getByRole('textbox', { name: 'Location Name' }).press('ScrollLock');
  await page.getByRole('textbox', { name: 'Location Name' }).click();
  await page.getByRole('textbox', { name: 'Location Name' }).fill('C2 Pune Ho');
  await page.getByRole('combobox', { name: 'Country' }).click();
  await page.getByRole('option', { name: 'India' }).click();
  await page.getByRole('combobox', { name: 'State' }).click();
  await page.getByRole('option', { name: 'Maharashtra' }).click();
  await page.getByRole('combobox', { name: 'City' }).click();
  await page.getByRole('option', { name: 'Pune', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address' }).click();
  await page.getByRole('textbox', { name: 'Address' }).fill('Pune');
  await page.getByRole('textbox', { name: 'Address' }).press('ScrollLock');
  await page.getByRole('textbox', { name: 'Address' }).fill('Pune, maharashtra');
  await page.getByRole('textbox', { name: 'Branch Code' }).click();
  await page.getByRole('textbox', { name: 'Branch Code' }).fill('PUNHO00123');
  await page.getByRole('spinbutton', { name: 'Pincode' }).click();
  await page.getByRole('spinbutton', { name: 'Pincode' }).fill('325234');
  await page.getByRole('combobox', { name: 'Location Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Department' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company' }).click();
  await page.getByRole('combobox', { name: 'Location' }).click();
  await page.getByRole('option', { name: 'C2 Pune Ho' }).press('ScrollLock');
  await page.getByRole('option', { name: 'C2 Pune Ho' }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).fill('DEPT1');
  await page.getByRole('combobox', { name: 'Department Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Department Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Department Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Department Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Department Name' }).fill('C1DEPT1');
  await page.getByRole('textbox', { name: 'Department Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Department Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Department Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Department Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Department Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Department Name' }).fill('C2DEPTA');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Role' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).press('ScrollLock');
  await page.getByRole('textbox', { name: 'Description' }).fill('Admin Role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Admin' }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Role Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Role Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Role Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Role Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C1Admin');
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C1orgAdmin');
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).press('ScrollLock');
  await page.getByRole('textbox', { name: 'Role Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Role Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Role Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Role Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Role Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Role Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Role Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C2OrgAdmin');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Role' }).getByTestId('ArrowRightIcon').click();
  await page.getByRole('menuitem', { name: 'View List' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Role' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C1Auditor');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('auditor r');
  await page.getByRole('textbox', { name: 'Description' }).press('ScrollLock');
  await page.getByRole('textbox', { name: 'Description' }).fill('auditor role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Auditor', exact: true }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C1Auditee');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('auditee role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Auditee', exact: true }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).fill('C1Mgmt');
  await page.getByRole('combobox', { name: 'Select Product' }).press('ScrollLock');
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByText('No options').click();
  await page.getByRole('combobox', { name: 'Select Product' }).fill('');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.locator('#menu-roleType > .MuiBackdrop-root').click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C1Mgmt');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('management role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Management' }).click();
  await page.getByRole('combobox', { name: 'Access' }).click();
  await page.getByRole('option', { name: 'Organization' }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();

  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c1Compa');
  await page.getByRole('textbox', { name: 'Username:' }).press('ScrollLock');
  await page.getByRole('textbox', { name: 'Username:' }).fill('c1CompanyAdmin');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).fill('Vish@12345');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).fill('c1Companyadmin');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username:' }).fill('c1companyadmin');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('c1company');
  await page.getByRole('textbox', { name: 'Email:' }).press('ScrollLock');
  await page.getByRole('textbox', { name: 'Email:' }).fill('c1companyadmin@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).click();
  await page.getByRole('textbox', { name: 'First Name:' }).fill('company');
  await page.getByRole('textbox', { name: 'First Name:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'First Name:' }).fill('c1company');
  await page.getByRole('textbox', { name: 'First Name:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'First Name:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'First Name:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'First Name:' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Last Name:' }).click();
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('admin');
  await page.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 23232-32323');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'c1orgadmin' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'Mumbai Ho' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'C1DEPTA' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Save' }).press('ScrollLock');

  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c1companyauditor');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).fill('Vish@12345');
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('c1companyauditor@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).click();
  await page.getByRole('textbox', { name: 'First Name:' }).fill('c1');
  await page.getByRole('textbox', { name: 'First Name:' }).press('ScrollLock');
  await page.getByRole('textbox', { name: 'Last Name:' }).click();
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('companyauditor');
  await page.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page.getByRole('button', { name: 'India: +' }).click();
  await page.getByText('India', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 32323-43454');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'c1auditor' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'Mumbai Ho' }).click();
  await page.locator('div:nth-child(13)').click();
  await page.getByRole('option', { name: 'C1DEPTA' }).click();
  await page.getByRole('button', { name: 'Signature' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Name' }).fill('c1compan');
  await page.getByRole('textbox', { name: 'Enter Your Name' }).press('ScrollLock');
  await page.getByRole('textbox', { name: 'Enter Your Name' }).fill('c1companyauditor');
  await page.getByRole('button', { name: 'Upload' }).nth(1).click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c1cmpanyauditee');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).fill('Vish@12345');
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('c1companyauditee@gmail');
  await page.getByRole('textbox', { name: 'Email:' }).press('ScrollLock');
  await page.getByRole('textbox', { name: 'Email:' }).fill('c1companyauditee@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Username:' }).fill('c1companyauditee');
  await page.getByRole('textbox', { name: 'First Name:' }).click();
  await page.getByRole('textbox', { name: 'First Name:' }).fill('company');
  await page.getByRole('textbox', { name: 'Last Name:' }).click();
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('c1auditee');
  await page.getByRole('button', { name: 'India: +' }).click();
  await page.getByRole('option', { name: 'India+' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 54545-45454');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'c1auditee' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('combobox', { name: 'Select Status: ACTIVE' }).press('ScrollLock');
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'Mumbai Ho' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'C1DEPTA' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'View List' }).click();
});