import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {

  await page.goto('http://localhost:8080/realms/aspl-realm/protocol/openid-connect/auth?response_type=code&client_id=aspl-open-id&redirect_uri=http%3A%2F%2Flocalhost%3A3000&code_challenge=UW0Eb3jCQySRSm6IYatJ1DfOG3EhgglgD-rdEW9uM90&code_challenge_method=S256&scope=profile+openid&state=customLoginState');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('vishalp');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div').filter({ hasText: 'AMS' }).nth(4).click();
  // --------------------- CREATE ORGANIZATION ---------------------
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Organization' }).click();
  await page.getByRole('menuitem', { name: 'Create Organization' }).click();
  await page.getByRole('textbox', { name: 'Organization Name' }).fill('Company2');
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Category' }).fill('State Cooperative Bank');
  await page.getByRole('combobox', { name: 'Organization Domain' }).click();
  await page.getByRole('option', { name: 'Banking' }).click();
  await page.getByRole('button', { name: 'Organization Logo' }).setInputFiles('logo.png');
  await page.getByRole('button', { name: 'Save' }).click();
  // --------------------- CREATE LOCATION ---------------------
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Location' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('textbox', { name: 'Location Name' }).fill('C2 Delhi HO');
  await page.getByRole('combobox', { name: 'Country' }).click();
  await page.getByRole('option', { name: 'India' }).click();
  await page.getByRole('combobox', { name: 'State' }).click();
  await page.getByRole('option', { name: 'Delhi' }).click();
  await page.getByRole('combobox', { name: 'City' }).click();
  await page.getByRole('option', { name: 'Delhi' }).click();
  await page.getByRole('textbox', { name: 'Address' }).fill('Delhi');
  await page.getByRole('textbox', { name: 'Branch Code' }).fill('DELHO001');
  await page.getByRole('spinbutton', { name: 'Pincode' }).fill('110001');
  await page.getByRole('combobox', { name: 'Location Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Location' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('textbox', { name: 'Location Name' }).fill('C2 Chennai Branch');
  await page.getByRole('combobox', { name: 'Country' }).click();
  await page.getByRole('option', { name: 'India' }).click();
  await page.getByRole('combobox', { name: 'State' }).click();
  await page.getByRole('option', { name: 'Tamil Nadu' }).click();
  await page.getByRole('combobox', { name: 'City' }).click();
  await page.getByRole('option', { name: 'Chennai' }).click();
  await page.getByRole('textbox', { name: 'Address' }).fill('Chennai, Tamil Nadu');
  await page.getByRole('textbox', { name: 'Branch Code' }).fill('CHEBR001');
  await page.getByRole('spinbutton', { name: 'Pincode' }).fill('600001');
  await page.getByRole('combobox', { name: 'Location Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  // --------------------- CREATE DEPARTMENTS ---------------------
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Department' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Location' }).click();
  await page.getByRole('option', { name: 'C2 Delhi HO' }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).fill('C1DEPTA');
  await page.getByRole('combobox', { name: 'Department Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Location' }).click();
  await page.getByRole('option', { name: 'C2 Delhi HO' }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).fill('C1DEPTB');
  await page.getByRole('combobox', { name: 'Department Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Location' }).click();
  await page.getByRole('option', { name: 'C2 Chennai Branch' }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).fill('C1DEPTC');
  await page.getByRole('combobox', { name: 'Department Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Location' }).click();
  await page.getByRole('option', { name: 'C2 Chennai Branch' }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).fill('C1DEPTD');
  await page.getByRole('combobox', { name: 'Department Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  // --------------------- CREATE ROLES ---------------------
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Role' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C2OrgAdmin');
  await page.getByRole('textbox', { name: 'Description' }).fill('Org admin role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Admin' }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Role' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C2Auditor');
  await page.getByRole('textbox', { name: 'Description' }).fill('Auditor role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Auditor' }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Role' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('C2Auditee');
  await page.getByRole('textbox', { name: 'Description' }).fill('Auditee role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Auditee' }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  // --------------------- CREATE USERS ---------------------
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c2admin');
  await page.getByRole('textbox', { name: 'Password:' }).fill('c2admin@12345');
  await page.getByRole('textbox', { name: 'Email:' }).fill('c2admin@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).fill('C2');
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('ADMIN');
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 11111-22222');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'C2OrgAdmin' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'C2 Delhi HO' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'C1DEPTA' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'View List', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c2auditor1');
  await page.getByRole('textbox', { name: 'Password:' }).fill('c2auditor1@12345');
  await page.getByRole('textbox', { name: 'Email:' }).fill('c2auditor1@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).fill('C2 AUDITOR1');
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('(DELHI HO)');
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 22222-33333');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'C2Auditor' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE' }).click();
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'C2 Delhi HO' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'C1DEPTA' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'View List', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c2auditee1');
  await page.getByRole('textbox', { name: 'Password:' }).fill('c2auditee1@12345');
  await page.getByRole('textbox', { name: 'Email:' }).fill('c2auditee1@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).fill('C2 AUDITEE1');
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('(DELHI HO)');
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 33333-44444');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'C2Auditee' }).click();
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'C2 Delhi HO' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'C1DEPTA' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'View List' }).click();
});