import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8080/realms/aspl-realm/protocol/openid-connect/auth?response_type=code&client_id=aspl-open-id&redirect_uri=http%3A%2F%2Flocalhost%3A3000&code_challenge=njtz_f1PMIJ065impB6A6pDniZPCS7xebWvJlJu_ODc&code_challenge_method=S256&scope=profile+openid&state=customLoginState');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('bhaskar');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div').filter({ hasText: 'AMS' }).nth(4).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Organization' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('textbox', { name: 'Organization Name' }).click();
  await page.getByRole('textbox', { name: 'Organization Name' }).fill('Company2');
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Category' }).click();
  await page.getByRole('textbox', { name: 'Category' }).dblclick();
  await page.getByRole('textbox', { name: 'Category' }).fill('State Cooperative Bank');
  await page.getByRole('combobox', { name: 'Organization Domain' }).click();
  await page.getByRole('option', { name: 'Banking' }).click();
  await page.getByRole('combobox', { name: 'Organization Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Organization Logo' }).click();
  await page.getByRole('button', { name: 'Organization Logo' }).setInputFiles('download.jpg');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Organization' }).click();
  await page.getByRole('menuitem', { name: 'View List' }).click();

  // Location creation
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Location' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('textbox', { name: 'Location Name' }).click();
  await page.getByRole('textbox', { name: 'Location Name' }).fill('Delhi');
  await page.getByRole('combobox', { name: 'Country' }).click();
  await page.getByRole('option', { name: 'India' }).click();
  await page.getByRole('combobox', { name: 'State' }).click();
  await page.getByRole('option', { name: 'Delhi' }).click();
  await page.getByRole('combobox', { name: 'City' }).click();
  await page.getByRole('option', { name: 'Old Delhi' }).click();
  await page.getByRole('textbox', { name: 'Address' }).click();
  await page.getByRole('textbox', { name: 'Address' }).fill('Old Rajendra Nagar - 412304');
  await page.getByRole('textbox', { name: 'Branch Code' }).click();
  await page.getByRole('textbox', { name: 'Branch Code' }).fill('Branch000123');
  await page.getByRole('spinbutton', { name: 'Pincode' }).click();
  await page.getByRole('spinbutton', { name: 'Pincode' }).fill('110001');
  await page.getByRole('combobox', { name: 'Location Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('combobox', { name: 'Head Office' }).click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Location' }).click();
  await page.getByRole('menuitem', { name: 'View List' }).click();

  // Department Creation
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Department' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Location' }).click();
  await page.getByRole('option', { name: 'Delhi' }).click();
  await page.getByRole('textbox', { name: 'Department Name' }).fill('Banking Department');
  await page.getByRole('combobox', { name: 'Department Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Department' }).getByTestId('ArrowRightIcon').click();
  await page.getByRole('menuitem', { name: 'View List' }).click();

  //  Role creation
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Role' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('c2stauditor1');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('This is statutory auditor');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'EXTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Statutory_Auditor' }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('c2auditee1');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('This is auditee role');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Auditee', exact: true }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('c2auditorr');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('This is auditor reviewer role.');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Auditor_Reviewer' }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('combobox', { name: 'Select Product' }).click();
  await page.getByRole('option', { name: 'AMS' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).click();
  await page.getByRole('textbox', { name: 'Role Name' }).fill('c2auditeer');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('This is auditee reviewer');
  await page.getByRole('combobox', { name: 'Role Type' }).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('combobox', { name: 'System Defined Roles' }).click();
  await page.getByRole('option', { name: 'Auditee_Reviewer' }).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c2stauditor1');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).fill('C2stauditor1@');
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('c2stauditor1@gmail.com');
  await page.locator('.MuiGrid-root > div:nth-child(4)').click();
  await page.getByRole('textbox', { name: 'First Name:' }).fill('c2');
  await page.getByRole('textbox', { name: 'Last Name:' }).click();
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('stauditor1');
  await page.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 90887-32211');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'c2stauditor1' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('textbox', { name: 'FRN Number:' }).click();
  await page.getByRole('textbox', { name: 'FRN Number:' }).fill('FRN00125');
  await page.getByRole('textbox', { name: 'Firm Name:' }).click();
  await page.getByRole('textbox', { name: 'Firm Name:' }).fill('HP');
  await page.getByRole('textbox', { name: 'Membership Number:' }).click();
  await page.getByRole('textbox', { name: 'Membership Number:' }).fill('MNO8421154675');
  await page.getByRole('button', { name: 'Signature' }).click();
  await page.locator('.MuiBackdrop-root.MuiModal-backdrop.css-1rxxzfv-MuiBackdrop-root').click({
    modifiers: ['ControlOrMeta']
  });
  await page.getByRole('textbox', { name: 'Enter Your Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Name' }).fill('c2stauditor1');
  await page.getByRole('combobox', { name: 'Font Family' }).click();
  await page.locator('#menu- > .MuiBackdrop-root').click();
  await page.getByRole('combobox', { name: 'Font Family' }).click();
  await page.getByRole('option', { name: 'Dancing Script' }).click();
  await page.getByRole('combobox', { name: 'Font Style' }).click();
  await page.getByRole('option', { name: 'Bold', exact: true }).click();
  await page.getByRole('button', { name: 'Upload' }).nth(1).click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.getByRole('button', { name: 'Save' }).click();

  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).getByTestId('ArrowRightIcon').click();
  await page.getByRole('menuitem', { name: 'View List' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).getByTestId('ArrowRightIcon').click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c2auditor1');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).fill('C2auditor1@');
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('c2auditor1@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).click();
  await page.getByRole('textbox', { name: 'First Name:' }).fill('c2');
  await page.getByRole('textbox', { name: 'Last Name:' }).click();
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('c2auditor1');
  await page.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 98780-09887');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'c2auditee1' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c2auditee');
  await page.getByRole('textbox', { name: 'Password:' }).dblclick();
  await page.getByRole('textbox', { name: 'Password:' }).fill('C2auditee1@');
  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c2auditee1');
  await page.getByRole('textbox', { name: 'Email:' }).dblclick();
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email:' }).fill('c2auditee1@gmail.com');
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'Delhi' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'Banking Department' }).click();
  await page.getByRole('button', { name: 'Save' }).click();

  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'Create', exact: true }).click();
  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c2auditorr');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).fill('C2auditorr1@');
  await page.getByRole('textbox', { name: 'Username:' }).dblclick();
  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c2auditorr1');
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('c2auditorr1@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).click();
  await page.getByRole('textbox', { name: 'First Name:' }).fill('c2');
  await page.getByRole('textbox', { name: 'Last Name:' }).click();
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('auditorr1');
  await page.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+87 43244-3233');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'c2auditorr' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 90875-54423');
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'Delhi' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'Banking Department' }).click();
  await page.getByRole('button', { name: 'Save' }).click();

  await page.getByRole('textbox', { name: 'Username:' }).click();
  await page.getByRole('textbox', { name: 'Username:' }).fill('c2auditeer1');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).fill('C2auditeer1@');
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('c2auditeer1@gmail.com');
  await page.getByRole('textbox', { name: 'First Name:' }).click();
  await page.getByRole('textbox', { name: 'First Name:' }).fill('c2');
  await page.getByRole('textbox', { name: 'Last Name:' }).click();
  await page.getByRole('textbox', { name: 'Last Name:' }).fill('auditeer1');
  await page.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 90872-31134');
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Select Role:' }).click();
  await page.getByRole('option', { name: 'c2auditeer' }).click();
  await page.getByRole('combobox', { name: 'Select Status:' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('combobox', { name: 'Select Location:' }).click();
  await page.getByRole('option', { name: 'Delhi' }).click();
  await page.getByRole('combobox', { name: 'Select Departments:' }).click();
  await page.getByRole('option', { name: 'Banking Department' }).click();
  await page.getByRole('button', { name: 'Save' }).click();

  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'User' }).click();
  await page.getByRole('menuitem', { name: 'View List' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();

  // create Risk Type
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
  await page.getByRole('textbox', { name: 'Risk-type' }).click();
  await page.getByRole('textbox', { name: 'Risk-type' }).fill('Stakeholder Risk');
  await page.getByRole('combobox', { name: 'Status Active' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('textbox', { name: 'Risk-type' }).click();
  await page.getByRole('textbox', { name: 'Risk-type' }).fill('Reputational Risk');
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Risk-type' }).click();
  await page.getByRole('textbox', { name: 'Risk-type' }).fill('Vendor Risk');
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Select status' }).press('NumLock');
  await page.getByRole('option', { name: 'Select status' }).press('ScrollLock');
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
  await page.getByRole('menuitem', { name: 'Risk Type' }).click();
  await page.getByRole('menuitem', { name: 'View List' }).click();

  // Problem
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
  await page.getByRole('menuitem', { name: 'Root Cause' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Problem' }).click();
  await page.getByRole('menuitem', { name: 'Create Problem' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('textbox', { name: 'Problem' }).click();
  await page.getByRole('textbox', { name: 'Problem' }).fill('C2Problem1');
  await page.getByRole('textbox', { name: 'Select Color' }).click();
  await page.getByRole('textbox', { name: 'Select Color' }).fill('#b65454');
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('combobox', { name: 'Status Active' }).press('NumLock');
  await page.getByRole('combobox', { name: 'Status Active' }).press('ScrollLock');
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('textbox', { name: 'Problem' }).click();
  await page.getByRole('textbox', { name: 'Problem' }).fill('C2Problem2');
  await page.getByRole('textbox', { name: 'Select Color' }).click();
  await page.getByRole('textbox', { name: 'Select Color' }).fill('#8b5050');
  await page.locator('div').filter({ hasText: 'Create' }).nth(3).click();
  await page.locator('div').filter({ hasText: 'Create' }).nth(3).click();
  await page.locator('div').filter({ hasText: 'Create' }).nth(3).click();
  await page.locator('div').filter({ hasText: 'Create' }).nth(3).click();
  await page.locator('div').filter({ hasText: 'Create' }).nth(3).click();
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
  await page.getByRole('menuitem', { name: 'Problem' }).click();
  await page.getByRole('menuitem', { name: 'View List' }).click();

  // Root Cause
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
  await page.getByRole('menuitem', { name: 'Root Cause' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Problem' }).click();
  await page.getByRole('option', { name: 'C2Problem1' }).click();
  await page.getByRole('textbox', { name: 'RootCause' }).click();
  await page.getByRole('textbox', { name: 'RootCause' }).fill('C2P1Cause1');
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('combobox', { name: 'Problem' }).click();
  await page.getByRole('option', { name: 'C2Problem2' }).click();
  await page.getByRole('textbox', { name: 'RootCause' }).click();
  await page.getByRole('textbox', { name: 'RootCause' }).fill('C');
  await page.getByRole('textbox', { name: 'RootCause' }).press('Shift+NumLock');
  await page.getByRole('textbox', { name: 'RootCause' }).press('Shift+ScrollLock');
  await page.getByRole('textbox', { name: 'RootCause' }).fill('C2P2Cause1');
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
  await page.getByRole('menuitem', { name: 'Cause' }).click();
  await page.getByRole('menuitem', { name: 'View List' }).click();

  //  create subcause
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'SubCause' }).click();
  await page.getByRole('menuitem', { name: 'Create SubCause' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Problem' }).click();
  await page.getByRole('option', { name: 'C2Problem1' }).click();
  await page.getByRole('combobox', { name: 'Root Cause' }).click();
  await page.getByRole('option', { name: 'C2P1Cause1' }).click();
  await page.getByRole('textbox', { name: 'Sub-Cause' }).click();
  await page.getByRole('textbox', { name: 'Sub-Cause' }).fill('C2P1C1Subcause1');
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('combobox', { name: 'Problem' }).click();
  await page.getByRole('option', { name: 'C2Problem2' }).click();
  await page.getByRole('combobox', { name: 'Problem C2Problem2' }).click();
  await page.getByRole('option', { name: 'C2Problem2' }).click();
  await page.getByRole('combobox', { name: 'Root Cause' }).click();
  await page.getByRole('option', { name: 'C2P2Cause1' }).click();
  await page.getByRole('textbox', { name: 'Sub-Cause' }).click();
  await page.getByRole('textbox', { name: 'Sub-Cause' }).fill('C');
  await page.getByRole('textbox', { name: 'Sub-Cause' }).press('NumLock');
  await page.getByRole('textbox', { name: 'Sub-Cause' }).press('ScrollLock');
  await page.getByRole('textbox', { name: 'Sub-Cause' }).fill('C2P2C1Subcause1');
  await page.getByRole('combobox', { name: 'Status' }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Audit Masters' }).click();
  await page.getByRole('menuitem', { name: 'SubCause' }).click();
  await page.getByRole('menuitem', { name: 'View List' }).click();

  await page.goto('http://localhost:8080/realms/aspl-realm/protocol/openid-connect/auth?response_type=code&client_id=aspl-open-id&redirect_uri=http%3A%2F%2Flocalhost%3A3000&code_challenge=AnjD85igQcKo_wgQlAS2mJRQiNgLe1t2_p1yeMdRpAQ&code_challenge_method=S256&scope=profile+openid&state=customLoginState');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('bhaskar');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div').filter({ hasText: 'AMS' }).nth(4).click();

  // create audit type
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Audit Type' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Select Report Type' }).first().click();
  await page.getByRole('option', { name: 'Tabular' }).click();
  await page.getByRole('textbox', { name: 'Select Color' }).click();
  await page.getByRole('textbox', { name: 'Select Color' }).fill('#4ed075');
  await page.getByRole('textbox', { name: 'Audit Type Name' }).click();
  await page.getByRole('textbox', { name: 'Audit Type Name' }).fill('Statutory-AuditType');
  await page.getByRole('combobox', { name: 'Audit Type Status' }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('combobox', { name: 'Audit Scoring Method' }).click();
  await page.getByRole('option', { name: 'None' }).click();
  await page.getByRole('combobox', { name: 'Loan Scoring Method' }).click();
  await page.getByRole('option', { name: 'Quarterly' }).click();
  await page.getByRole('spinbutton', { name: 'Finding Closure Duration (in' }).click();
  await page.getByRole('spinbutton', { name: 'Finding Closure Duration (in' }).fill('4');
  await page.getByRole('combobox', { name: 'Select Report Type' }).nth(1).click();
  await page.getByRole('option', { name: 'INTERNAL' }).click();
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('This is a statutory audit type.');
  await page.getByRole('combobox', { name: 'Loan Scoring Method' }).click();
  await page.getByRole('radio', { name: 'Yes' }).check();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('form').click();
  await page.getByRole('paragraph').filter({ hasText: 'Audit Type InformationOrganizationCompany2Organization *Select Report' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('button', { name: 'Add Row' }).first().click();
  await page.getByRole('button', { name: 'Add Row' }).first().click();
  await page.getByRole('button', { name: 'Add Row' }).first().click();
  await page.getByRole('textbox', { name: 'Compliance' }).first().click();
  await page.getByRole('textbox', { name: 'Compliance' }).first().fill('Yes');
  await page.getByRole('row', { name: 'Delete Row Yes #000000 Add Row' }).getByRole('emphasis').click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByRole('row', { name: 'Delete Row Yes #000000 Add Row' }).getByLabel('NO').check();
  await page.getByRole('row', { name: 'Delete Row Yes #000000 Add Row' }).getByPlaceholder('Weightage').click();
  await page.getByRole('row', { name: 'Delete Row Yes #000000 Add Row' }).getByPlaceholder('Weightage').fill('0');
  await page.getByRole('row', { name: 'Delete Row Yes #000000 Add Row' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: 'Delete Row Yes 0 #000000 Add' }).locator('input[type="color"]').fill('#ac784d');
  await page.getByRole('textbox', { name: 'Compliance' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Compliance' }).nth(1).fill('NA');
  await page.getByRole('row', { name: 'Delete Row NA #000000 Add Row' }).getByRole('emphasis').click();
  await page.getByRole('option', { name: 'NA' }).click();
  await page.getByRole('row', { name: 'Delete Row NA #000000 Add Row' }).getByLabel('NO').check();
  await page.getByRole('row', { name: 'Delete Row NA #000000 Add Row' }).getByPlaceholder('Weightage').click();
  await page.getByRole('row', { name: 'Delete Row NA #000000 Add Row' }).getByPlaceholder('Weightage').fill('0');
  await page.getByRole('row', { name: 'Delete Row NA #000000 Add Row' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: 'Delete Row NA 0 #000000 Add' }).locator('input[type="color"]').fill('#d2bc4b');
  await page.getByRole('row', { name: 'Delete Row #000000 Add Row' }).getByPlaceholder('Compliance').click();
  await page.getByRole('row', { name: 'Delete Row #000000 Add Row' }).getByPlaceholder('Compliance').fill('No');
  await page.getByText('Select').click();
  await page.getByRole('option', { name: 'NA' }).click();
  await page.getByRole('row', { name: 'Delete Row No #000000 Add Row' }).getByRole('combobox').click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.getByRole('row', { name: 'Delete Row No #000000 Add Row' }).getByLabel('YES').check();
  await page.getByRole('row', { name: 'Delete Row No #000000 Add Row' }).getByPlaceholder('Sub Answer').click();
  await page.getByRole('row', { name: 'Delete Row No #000000 Add Row' }).getByPlaceholder('Sub Answer').fill('Low');
  await page.getByRole('row', { name: 'Delete Row No Low #000000 Add' }).getByPlaceholder('Weightage').click();
  await page.getByRole('row', { name: 'Delete Row No Low #000000 Add' }).getByPlaceholder('Weightage').fill('0');
  await page.getByRole('row', { name: 'Delete Row No Low #000000 Add' }).getByLabel('Add Row').dblclick();
  await page.getByRole('row', { name: 'Delete Row No Low #000000 Add' }).getByLabel('Add Row').click();
  await page.getByRole('textbox', { name: 'Sub Answer' }).nth(3).fill('Medium');
  await page.getByRole('cell', { name: 'H' }).getByPlaceholder('Sub Answer').fill('High');
  await page.getByRole('row', { name: 'Delete Row No Low 0 #000000' }).getByLabel('Add Row').click();
  await page.getByRole('row', { name: '#000000 Delete Row', exact: true }).getByPlaceholder('Sub Answer').click();
  await page.getByRole('cell', { name: 'V' }).getByPlaceholder('Sub Answer').fill('Very High');
  await page.getByRole('row', { name: 'Medium #000000 Delete Row' }).getByPlaceholder('Weightage').click();
  await page.getByRole('row', { name: 'Medium #000000 Delete Row' }).getByPlaceholder('Weightage').fill('0');
  await page.getByRole('row', { name: 'High #000000 Delete Row', exact: true }).getByPlaceholder('Weightage').click();
  await page.getByRole('row', { name: 'Medium 00 #000000 Delete Row' }).getByPlaceholder('Weightage').click();
  await page.getByRole('row', { name: 'Medium 00 #000000 Delete Row' }).getByPlaceholder('Weightage').fill('0');
  await page.getByRole('row', { name: 'High #000000 Delete Row', exact: true }).getByPlaceholder('Weightage').click();
  await page.getByRole('row', { name: 'High #000000 Delete Row', exact: true }).getByPlaceholder('Weightage').fill('0');
  await page.getByRole('row', { name: 'Very High #000000 Delete Row' }).getByPlaceholder('Weightage').click();
  await page.getByRole('row', { name: 'Very High #000000 Delete Row' }).getByPlaceholder('Weightage').fill('0');
  await page.getByRole('row', { name: 'Delete Row No Low 0 #000000' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: 'Delete Row No Low 0 #000000' }).locator('input[type="color"]').fill('#7d57a2');
  await page.getByRole('cell', { name: '#000000' }).nth(1).click();
  await page.getByRole('row', { name: 'Medium 0 #000000 Delete Row' }).locator('input[type="color"]').fill('#376115');
  await page.getByRole('row', { name: 'High 0 #000000 Delete Row', exact: true }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: 'High 0 #000000 Delete Row', exact: true }).locator('input[type="color"]').fill('#bd8989');
  await page.getByRole('row', { name: 'Very High 0 #000000 Delete Row' }).locator('input[type="color"]').click();
  await page.getByRole('row', { name: 'Very High 0 #000000 Delete Row' }).locator('input[type="color"]').fill('#e67070');
  await page.getByRole('button', { name: 'Add Row' }).nth(2).dblclick();
  await page.locator('[id=":r4u:"]').click();
  await page.locator('[id=":r4u:"]').fill('Openc');
  await page.locator('[id=":r52:"]').click();
  await page.locator('[id=":r52:"]').fill('Closed');
  await page.getByRole('cell', { name: 'System Alias' }).first().click();
  await page.getByRole('option', { name: 'Open' }).click();
  await page.getByRole('combobox', { name: 'System Alias', exact: true }).click();
  await page.getByRole('option', { name: 'Closed' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Click Next to Proceed' }).click();
  await page.getByRole('button', { name: 'Add Row' }).dblclick();
  await page.getByRole('button', { name: 'Add Row' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('Open');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('WIP');
  await page.getByRole('row', { name: 'System Alias Remove Row', exact: true }).getByRole('textbox').click();
  await page.getByRole('row', { name: 'System Alias Remove Row', exact: true }).getByRole('textbox').fill('Completed');
  await page.getByRole('row', { name: 'Open System Alias Remove Row' }).getByLabel('System Alias').click();
  await page.getByRole('option', { name: 'Open' }).click();
  await page.getByRole('option', { name: 'Open' }).click();
  await page.getByRole('row', { name: 'WIP System Alias Remove Row' }).getByLabel('System Alias').click();
  await page.getByRole('option', { name: 'Wip' }).click();
  await page.getByRole('row', { name: 'Completed System Alias Remove' }).getByLabel('System Alias').click();
  await page.getByRole('option', { name: 'Completed' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Finish' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();


  //  create workflow
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Workflow' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('option', { name: 'Statutory-AuditType' }).click();
  await page.getByRole('textbox', { name: 'Workflow Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Name' }).fill('Statutory-Workflow');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Workflow', exact: true }).click();
  await page.getByRole('menuitem', { name: 'View List' }).click();

  //  create workflow Stages
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Workflow Stages' }).click();
  await page.getByRole('menuitem', { name: 'Create' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Planned');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Created');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Document Upload');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click({
    modifiers: ['Shift']
  });
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit In Progress');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click({
    modifiers: ['Shift']
  });
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Completed');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Compliance Inprogress');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Compliance IN progress');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Compliance Verification');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).click({
    modifiers: ['Shift']
  });
  await page.getByRole('textbox', { name: 'Workflow Stage Name' }).fill('Audit Closed');
  await page.getByRole('combobox', { name: 'Audit Type', exact: true }).click();
  await page.getByRole('option', { name: 'ACTIVE', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Workflow Stages' }).click();
  await page.getByRole('menuitem', { name: 'View List' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Workflow' }).click();
  await page.getByRole('option', { name: 'Statutory-Workflow' }).click();

  await page.getByText('OrganizationOrganization *Please Select Organization...').click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();

  // Assign sequence to workflow stages
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Workflow Stages' }).click();
  await page.getByRole('menuitem', { name: 'Assign Sequence To Stages' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Stage Workflow' }).click();
  await page.getByRole('option', { name: 'Statutory-Workflow' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Audit Planned' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('1');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Audit Created' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('2');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Document Upload' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('3');
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Audit In Progress' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('4');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Audit Completed' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('5');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Compliance Inprogress' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('6');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('7');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('combobox', { name: 'Select Workflow Stage' }).click();
  await page.getByRole('option', { name: 'Compliance Verification' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).click();
  await page.getByRole('spinbutton', { name: 'Workflow Stage Number' }).fill('8');
  await page.getByRole('button', { name: 'Submit' }).click();

  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Workflow Stages' }).click();
  await page.getByRole('menuitem', { name: 'View Sequence List' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Workflow' }).click();
  await page.getByRole('option', { name: 'Statutory-Workflow' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).click();
  await page.getByRole('menuitem', { name: 'Workflow Stages' }).click();
  await page.getByRole('menuitem', { name: 'Manage Workflow Access' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Audit Type' }).click();
  await page.getByRole('option', { name: 'Statutory-AuditType' }).click();
  await page.getByRole('combobox', { name: 'Role' }).click();
  await page.getByRole('option', { name: 'c2stauditor1' }).click();
  await page.getByTestId('CheckBoxOutlineBlankIcon').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(4) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(3) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(20) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(2) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(3) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(5) > td:nth-child(20) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(15) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(3) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(2) > td:nth-child(15) > .MuiSvgIcon-root').click();
  await page.locator('tr:nth-child(2) > td:nth-child(14) > .MuiSvgIcon-root').click();
  await page.locator('td:nth-child(14) > .MuiSvgIcon-root').first().click();
  await page.locator('tr:nth-child(3) > td:nth-child(18) > .MuiSvgIcon-root').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('menuitem', { name: 'Admin' }).getByTestId('ArrowDropDownIcon').click();
  await page.locator('.MuiPopover-root.MuiModal-root.css-tskh11-MuiModal-root-MuiPopover-root > .MuiBackdrop-root').click();

  // create Audit
  await page.goto('http://localhost:8080/realms/aspl-realm/protocol/openid-connect/auth?response_type=code&client_id=aspl-open-id&redirect_uri=http%3A%2F%2Flocalhost%3A3000&code_challenge=7OiLlMrpkI1ynCwIjDV5CbDv6c3zxdtfXRwhlrjDcSI&code_challenge_method=S256&scope=profile+openid&state=customLoginState');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('bhaskar');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div').filter({ hasText: 'AMS' }).nth(4).click();
  await page.getByRole('menuitem', { name: 'Audit' }).click();
  await page.getByRole('menuitem', { name: 'Audit Annual Plan' }).click();
  await page.getByRole('combobox', { name: 'Organization' }).click();
  await page.getByRole('option', { name: 'Company2' }).click();
  await page.getByRole('combobox', { name: 'Audit Type' }).click();
  await page.getByRole('option', { name: 'Statutory-AuditType' }).click();
  await page.getByRole('combobox', { name: 'Audit Plan for' }).click();
  await page.getByRole('option', { name: 'Calendar Year' }).click();
  await page.getByRole('button', { name: 'Generate', exact: true }).click();
  await page.getByRole('combobox', { name: 'Months of 2025' }).click();
  await page.getByRole('option', { name: 'Oct' }).click();
  await page.getByRole('button', { name: 'Generate Schedule' }).click();
  await page.getByRole('button', { name: 'Initiate Audit' }).click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'Audit Created' }).click();
  await page.getByRole('textbox', { name: 'Audit Name' }).click();
  await page.getByRole('textbox', { name: 'Audit Name' }).fill('Statutory-Oct10');
  await page.getByRole('textbox', { name: 'Planned Start Date' }).fill('2025-10-08');
  await page.getByRole('textbox', { name: 'Planned Start Time' }).click();
  await page.getByRole('textbox', { name: 'Planned Start Time' }).fill('10:29');
  await page.getByRole('textbox', { name: 'Planned Finish Date' }).fill('2025-11-08');
  await page.getByRole('textbox', { name: 'Planned Finish Time' }).click();
  await page.getByRole('textbox', { name: 'Planned Finish Time' }).fill('11:20');
  await page.getByRole('textbox', { name: 'Audit Period From' }).fill('2025-10-10');
  await page.getByRole('textbox', { name: 'Audit Period To' }).fill('2025-11-10');
  await page.getByRole('button', { name: 'Add Users +' }).click();
  await page.getByRole('button', { name: 'Add Users +' }).click();
  await page.getByRole('combobox', { name: 'Select User' }).first().click();
  await page.getByRole('option', { name: 'c2stauditor1-c2stauditor1' }).click();
  await page.getByRole('combobox', { name: 'Assign Audit Level Role' }).first().click();
  await page.getByText('other').nth(1).click();
  await page.getByRole('checkbox', { name: 'Is Lead Auditor?' }).check();
  await page.getByRole('combobox', { name: 'Select User' }).nth(1).click();
  await page.getByRole('combobox', { name: 'Select User' }).nth(1).click();
  await page.getByRole('option', { name: 'c2auditee1-c2auditee1' }).click();
  await page.getByRole('combobox', { name: 'Assign Audit Level Role' }).nth(1).click();
  await page.getByText('c2auditee1', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Audit Scope' }).click();
  await page.getByRole('textbox', { name: 'Audit Scope' }).fill('Audit scope');
  await page.getByRole('textbox', { name: 'Audit Objective' }).click();
  await page.getByRole('textbox', { name: 'Audit Objective' }).fill('Audit Objective');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('menuitem', { name: 'Audit' }).getByTestId('ArrowDropDownIcon').click();
  await page.getByRole('menuitem', { name: 'List View' }).click();
});